server:
  port: 8088
  context-path: /riska/rest
spring:
  data:
    mongodb:
      host: 60.30.111.99 #60.30.111.99
      database: riska
      port: 10005
      username: riskaAdmin
      password: riskaAdmin123QWE!@#
logging.level:
  org.springframework.data.mongodb.core.MongoTemplate: ERROR
