spring:
  data:
    mongodb:
      host: localhost
      database: riska
      port: 9999
      username: riskaAdmin
      password: riskaAdmin123QWE!@#
logging.level:
  org.springframework.data.mongodb.core.MongoTemplate: ERROR