package ksuserapistructex;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u05a4\u022f\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : KSUserApiStructEx.h:4886</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSUserApiStructEx") 
public class CThostFtdcStockDisposalField extends StructObject {
	public CThostFtdcStockDisposalField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u05a4\u022f\ufffd\ufffd\ufffd\u00f5\u01fc\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({13}) 
	@Field(2) 
	public Pointer<Byte > StockDisposalRef() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({16}) 
	@Field(3) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(4) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(5) 
	public int Volume() {
		return this.io.getIntField(this, 5);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(5) 
	public CThostFtdcStockDisposalField Volume(int Volume) {
		this.io.setIntField(this, 5, Volume);
		return this;
	}
	/**
	 * \u05a4\u022f\ufffd\ufffd\ufffd\u00f7\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcStockDisposalTypeType
	 */
	@Field(6) 
	public byte StockDisposalType() {
		return this.io.getByteField(this, 6);
	}
	/**
	 * \u05a4\u022f\ufffd\ufffd\ufffd\u00f7\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcStockDisposalTypeType
	 */
	@Field(6) 
	public CThostFtdcStockDisposalField StockDisposalType(byte StockDisposalType) {
		this.io.setByteField(this, 6, StockDisposalType);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u05a4\u022f\ufffd\ufffd\ufffd\u00f1\ufffd\ufffd<br>
	 * C type : TThostFtdcOrderLocalIDType
	 */
	@Array({13}) 
	@Field(7) 
	public Pointer<Byte > StockDisposalLocalID() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(8) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\u06bd\ufffd\ufffd\ufffd\ufffd\ufffd\u0134\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeInstIDType
	 */
	@Array({31}) 
	@Field(9) 
	public Pointer<Byte > ExchangeInstID() {
		return this.io.getPointerField(this, 9);
	}
	/**
	 * \ufffd\ufffd\u0531\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	@Array({11}) 
	@Field(10) 
	public Pointer<Byte > ParticipantID() {
		return this.io.getPointerField(this, 10);
	}
	/**
	 * \ufffd\u037b\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcClientIDType
	 */
	@Array({11}) 
	@Field(11) 
	public Pointer<Byte > ClientID() {
		return this.io.getPointerField(this, 11);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0531\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcTraderIDType
	 */
	@Array({21}) 
	@Field(12) 
	public Pointer<Byte > TraderID() {
		return this.io.getPointerField(this, 12);
	}
	/**
	 * \ufffd\ufffd\u05f0\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(13) 
	public int InstallID() {
		return this.io.getIntField(this, 13);
	}
	/**
	 * \ufffd\ufffd\u05f0\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(13) 
	public CThostFtdcStockDisposalField InstallID(int InstallID) {
		this.io.setIntField(this, 13, InstallID);
		return this;
	}
	/**
	 * \u05a4\u022f\ufffd\ufffd\ufffd\ufffd\u05f4\u032c<br>
	 * C type : TThostFtdcStockDisposalStatusType
	 */
	@Field(14) 
	public byte StockDisposalStatus() {
		return this.io.getByteField(this, 14);
	}
	/**
	 * \u05a4\u022f\ufffd\ufffd\ufffd\ufffd\u05f4\u032c<br>
	 * C type : TThostFtdcStockDisposalStatusType
	 */
	@Field(14) 
	public CThostFtdcStockDisposalField StockDisposalStatus(byte StockDisposalStatus) {
		this.io.setByteField(this, 14, StockDisposalStatus);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02be\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(15) 
	public int NotifySequence() {
		return this.io.getIntField(this, 15);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02be\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(15) 
	public CThostFtdcStockDisposalField NotifySequence(int NotifySequence) {
		this.io.setIntField(this, 15, NotifySequence);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({9}) 
	@Field(16) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 16);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSettlementIDType
	 */
	@Field(17) 
	public int SettlementID() {
		return this.io.getIntField(this, 17);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSettlementIDType
	 */
	@Field(17) 
	public CThostFtdcStockDisposalField SettlementID(int SettlementID) {
		this.io.setIntField(this, 17, SettlementID);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({9}) 
	@Field(18) 
	public Pointer<Byte > InsertDate() {
		return this.io.getPointerField(this, 18);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(19) 
	public Pointer<Byte > InsertTime() {
		return this.io.getPointerField(this, 19);
	}
	/**
	 * \u01f0\ufffd\u00f1\ufffd\ufffd<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(20) 
	public int FrontID() {
		return this.io.getIntField(this, 20);
	}
	/**
	 * \u01f0\ufffd\u00f1\ufffd\ufffd<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(20) 
	public CThostFtdcStockDisposalField FrontID(int FrontID) {
		this.io.setIntField(this, 20, FrontID);
		return this;
	}
	/**
	 * \ufffd\u1ef0\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(21) 
	public int SessionID() {
		return this.io.getIntField(this, 21);
	}
	/**
	 * \ufffd\u1ef0\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(21) 
	public CThostFtdcStockDisposalField SessionID(int SessionID) {
		this.io.setIntField(this, 21, SessionID);
		return this;
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\u03e2<br>
	 * C type : TThostFtdcProductInfoType
	 */
	@Array({11}) 
	@Field(22) 
	public Pointer<Byte > UserProductInfo() {
		return this.io.getPointerField(this, 22);
	}
	/**
	 * \u05f4\u032c\ufffd\ufffd\u03e2<br>
	 * C type : TThostFtdcErrorMsgType
	 */
	@Array({256}) 
	@Field(23) 
	public Pointer<Byte > StatusMsg() {
		return this.io.getPointerField(this, 23);
	}
	/**
	 * \u04ea\u04b5\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBranchIDType
	 */
	@Array({9}) 
	@Field(24) 
	public Pointer<Byte > BranchID() {
		return this.io.getPointerField(this, 24);
	}
	/**
	 * \u05a4\u022f\ufffd\ufffd\ufffd\u00f2\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcStockDisposalSysIDType
	 */
	@Array({21}) 
	@Field(25) 
	public Pointer<Byte > StockDisposalSysID() {
		return this.io.getPointerField(this, 25);
	}
	/**
	 * \u04b5\ufffd\ufffd\u052a<br>
	 * C type : TThostFtdcBusinessUnitType
	 */
	@Array({21}) 
	@Field(26) 
	public Pointer<Byte > BusinessUnit() {
		return this.io.getPointerField(this, 26);
	}
	public CThostFtdcStockDisposalField(Pointer pointer) {
		super(pointer);
	}
}
