package ksuserapistructex;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05a4\u022f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
 * <i>native declaration : KSUserApiStructEx.h:4956</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSUserApiStructEx") 
public class CThostFtdcExchangeStockDisposalField extends StructObject {
	public CThostFtdcExchangeStockDisposalField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(0) 
	public int Volume() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(0) 
	public CThostFtdcExchangeStockDisposalField Volume(int Volume) {
		this.io.setIntField(this, 0, Volume);
		return this;
	}
	/**
	 * \u05a4\u022f\ufffd\ufffd\ufffd\u00f7\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcStockDisposalTypeType
	 */
	@Field(1) 
	public byte StockDisposalType() {
		return this.io.getByteField(this, 1);
	}
	/**
	 * \u05a4\u022f\ufffd\ufffd\ufffd\u00f7\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcStockDisposalTypeType
	 */
	@Field(1) 
	public CThostFtdcExchangeStockDisposalField StockDisposalType(byte StockDisposalType) {
		this.io.setByteField(this, 1, StockDisposalType);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u05a4\u022f\ufffd\ufffd\ufffd\u00f1\ufffd\ufffd<br>
	 * C type : TThostFtdcOrderLocalIDType
	 */
	@Array({13}) 
	@Field(2) 
	public Pointer<Byte > StockDisposalLocalID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\u06bd\ufffd\ufffd\ufffd\ufffd\ufffd\u0134\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeInstIDType
	 */
	@Array({31}) 
	@Field(4) 
	public Pointer<Byte > ExchangeInstID() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \ufffd\ufffd\u0531\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	@Array({11}) 
	@Field(5) 
	public Pointer<Byte > ParticipantID() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \ufffd\u037b\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcClientIDType
	 */
	@Array({11}) 
	@Field(6) 
	public Pointer<Byte > ClientID() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0531\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcTraderIDType
	 */
	@Array({21}) 
	@Field(7) 
	public Pointer<Byte > TraderID() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \ufffd\ufffd\u05f0\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(8) 
	public int InstallID() {
		return this.io.getIntField(this, 8);
	}
	/**
	 * \ufffd\ufffd\u05f0\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(8) 
	public CThostFtdcExchangeStockDisposalField InstallID(int InstallID) {
		this.io.setIntField(this, 8, InstallID);
		return this;
	}
	/**
	 * \u05a4\u022f\ufffd\ufffd\ufffd\ufffd\u05f4\u032c<br>
	 * C type : TThostFtdcStockDisposalStatusType
	 */
	@Field(9) 
	public byte StockDisposalStatus() {
		return this.io.getByteField(this, 9);
	}
	/**
	 * \u05a4\u022f\ufffd\ufffd\ufffd\ufffd\u05f4\u032c<br>
	 * C type : TThostFtdcStockDisposalStatusType
	 */
	@Field(9) 
	public CThostFtdcExchangeStockDisposalField StockDisposalStatus(byte StockDisposalStatus) {
		this.io.setByteField(this, 9, StockDisposalStatus);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02be\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(10) 
	public int NotifySequence() {
		return this.io.getIntField(this, 10);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02be\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(10) 
	public CThostFtdcExchangeStockDisposalField NotifySequence(int NotifySequence) {
		this.io.setIntField(this, 10, NotifySequence);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({9}) 
	@Field(11) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 11);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSettlementIDType
	 */
	@Field(12) 
	public int SettlementID() {
		return this.io.getIntField(this, 12);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSettlementIDType
	 */
	@Field(12) 
	public CThostFtdcExchangeStockDisposalField SettlementID(int SettlementID) {
		this.io.setIntField(this, 12, SettlementID);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({9}) 
	@Field(13) 
	public Pointer<Byte > InsertDate() {
		return this.io.getPointerField(this, 13);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(14) 
	public Pointer<Byte > InsertTime() {
		return this.io.getPointerField(this, 14);
	}
	/**
	 * \u04ea\u04b5\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBranchIDType
	 */
	@Array({9}) 
	@Field(15) 
	public Pointer<Byte > BranchID() {
		return this.io.getPointerField(this, 15);
	}
	/**
	 * \u05a4\u022f\ufffd\ufffd\ufffd\u00f2\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcStockDisposalSysIDType
	 */
	@Array({21}) 
	@Field(16) 
	public Pointer<Byte > StockDisposalSysID() {
		return this.io.getPointerField(this, 16);
	}
	/**
	 * \u04b5\ufffd\ufffd\u052a<br>
	 * C type : TThostFtdcBusinessUnitType
	 */
	@Array({21}) 
	@Field(17) 
	public Pointer<Byte > BusinessUnit() {
		return this.io.getPointerField(this, 17);
	}
	public CThostFtdcExchangeStockDisposalField(Pointer pointer) {
		super(pointer);
	}
}
