package ksuserapistructex;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\u05b4\ufffd\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : KSUserApiStructEx.h:3101</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSUserApiStructEx") 
public class CThostFtdcErrExecOrderField extends StructObject {
	public CThostFtdcErrExecOrderField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(2) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u05b4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({13}) 
	@Field(3) 
	public Pointer<Byte > ExecOrderRef() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({16}) 
	@Field(4) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(5) 
	public int Volume() {
		return this.io.getIntField(this, 5);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(5) 
	public CThostFtdcErrExecOrderField Volume(int Volume) {
		this.io.setIntField(this, 5, Volume);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(6) 
	public int RequestID() {
		return this.io.getIntField(this, 6);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(6) 
	public CThostFtdcErrExecOrderField RequestID(int RequestID) {
		this.io.setIntField(this, 6, RequestID);
		return this;
	}
	/**
	 * \u04b5\ufffd\ufffd\u052a<br>
	 * C type : TThostFtdcBusinessUnitType
	 */
	@Array({21}) 
	@Field(7) 
	public Pointer<Byte > BusinessUnit() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(8) 
	public byte OffsetFlag() {
		return this.io.getByteField(this, 8);
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(8) 
	public CThostFtdcErrExecOrderField OffsetFlag(byte OffsetFlag) {
		this.io.setByteField(this, 8, OffsetFlag);
		return this;
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u05f1\ufffd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(9) 
	public byte HedgeFlag() {
		return this.io.getByteField(this, 9);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u05f1\ufffd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(9) 
	public CThostFtdcErrExecOrderField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 9, HedgeFlag);
		return this;
	}
	/**
	 * \u05b4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcActionTypeType
	 */
	@Field(10) 
	public byte ActionType() {
		return this.io.getByteField(this, 10);
	}
	/**
	 * \u05b4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcActionTypeType
	 */
	@Field(10) 
	public CThostFtdcErrExecOrderField ActionType(byte ActionType) {
		this.io.setByteField(this, 10, ActionType);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u0377\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0133\u05b2\u05b7\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPosiDirectionType
	 */
	@Field(11) 
	public byte PosiDirection() {
		return this.io.getByteField(this, 11);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u0377\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0133\u05b2\u05b7\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPosiDirectionType
	 */
	@Field(11) 
	public CThostFtdcErrExecOrderField PosiDirection(byte PosiDirection) {
		this.io.setByteField(this, 11, PosiDirection);
		return this;
	}
	/**
	 * \ufffd\ufffd\u0228\ufffd\ufffd\u0228\ufffd\ufffd\ufffd\u01f7\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\u0377\ufffd\ufffd\u0131\ufffd\ufffd<br>
	 * C type : TThostFtdcExecOrderPositionFlagType
	 */
	@Field(12) 
	public byte ReservePositionFlag() {
		return this.io.getByteField(this, 12);
	}
	/**
	 * \ufffd\ufffd\u0228\ufffd\ufffd\u0228\ufffd\ufffd\ufffd\u01f7\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\u0377\ufffd\ufffd\u0131\ufffd\ufffd<br>
	 * C type : TThostFtdcExecOrderPositionFlagType
	 */
	@Field(12) 
	public CThostFtdcErrExecOrderField ReservePositionFlag(byte ReservePositionFlag) {
		this.io.setByteField(this, 12, ReservePositionFlag);
		return this;
	}
	/**
	 * \ufffd\ufffd\u0228\ufffd\ufffd\u0228\ufffd\ufffd\ufffd\ufffd\u0275\ufffd\u0377\ufffd\ufffd\ufffd\u01f7\ufffd\ufffd\u0536\ufffd\u01bd\ufffd\ufffd<br>
	 * C type : TThostFtdcExecOrderCloseFlagType
	 */
	@Field(13) 
	public byte CloseFlag() {
		return this.io.getByteField(this, 13);
	}
	/**
	 * \ufffd\ufffd\u0228\ufffd\ufffd\u0228\ufffd\ufffd\ufffd\ufffd\u0275\ufffd\u0377\ufffd\ufffd\ufffd\u01f7\ufffd\ufffd\u0536\ufffd\u01bd\ufffd\ufffd<br>
	 * C type : TThostFtdcExecOrderCloseFlagType
	 */
	@Field(13) 
	public CThostFtdcErrExecOrderField CloseFlag(byte CloseFlag) {
		this.io.setByteField(this, 13, CloseFlag);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(14) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 14);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(15) 
	public int ErrorID() {
		return this.io.getIntField(this, 15);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(15) 
	public CThostFtdcErrExecOrderField ErrorID(int ErrorID) {
		this.io.setIntField(this, 15, ErrorID);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : TThostFtdcErrorMsgType
	 */
	@Array({256}) 
	@Field(16) 
	public Pointer<Byte > ErrorMsg() {
		return this.io.getPointerField(this, 16);
	}
	public CThostFtdcErrExecOrderField(Pointer pointer) {
		super(pointer);
	}
}
