package ksvocmdapi;
import ksuserapistructex.CThostFtdcRspInfoField;
import ksvocapistruct.CKSSpecificInstrumentField;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Virtual;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : KSVocMdApi.h:20</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocMdApi") 
public class CKSVocMdSpi extends CPPObject {
	public CKSVocMdSpi() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspSubKSMarketData(CKSSpecificInstrumentField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSVocMdApi.h:24</i>
	 */
	@Virtual(0) 
	public native void OnRspSubKSMarketData(Pointer<CKSSpecificInstrumentField > pSpecificInstrument, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u0221\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspUnSubKSMarketData(CKSSpecificInstrumentField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSVocMdApi.h:27</i>
	 */
	@Virtual(1) 
	public native void OnRspUnSubKSMarketData(Pointer<CKSSpecificInstrumentField > pSpecificInstrument, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	public CKSVocMdSpi(Pointer pointer) {
		super(pointer);
	}
}
