package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\u02bc\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : KSVocApiStruct.h:10</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSConditionalOrderInitInsert extends StructObject {
	public CKSConditionalOrderInitInsert() {
		super();
	}
	/**
	 * \u04ea\u04b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(2) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\u037b\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcClientIDType
	 */
	@Array({11}) 
	@Field(4) 
	public Pointer<Byte > ClientID() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(5) 
	public byte Direction() {
		return this.io.getByteField(this, 5);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(5) 
	public CKSConditionalOrderInitInsert Direction(byte Direction) {
		this.io.setByteField(this, 5, Direction);
		return this;
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(6) 
	public byte CombOffsetFlag() {
		return this.io.getByteField(this, 6);
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(6) 
	public CKSConditionalOrderInitInsert CombOffsetFlag(byte CombOffsetFlag) {
		this.io.setByteField(this, 6, CombOffsetFlag);
		return this;
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u05f1\ufffd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(7) 
	public byte CombHedgeFlag() {
		return this.io.getByteField(this, 7);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u05f1\ufffd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(7) 
	public CKSConditionalOrderInitInsert CombHedgeFlag(byte CombHedgeFlag) {
		this.io.setByteField(this, 7, CombHedgeFlag);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(8) 
	public int VolumeTotalOriginal() {
		return this.io.getIntField(this, 8);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(8) 
	public CKSConditionalOrderInitInsert VolumeTotalOriginal(int VolumeTotalOriginal) {
		this.io.setIntField(this, 8, VolumeTotalOriginal);
		return this;
	}
	/**
	 * \ufffd\u06f8\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(9) 
	public double LimitPrice() {
		return this.io.getDoubleField(this, 9);
	}
	/**
	 * \ufffd\u06f8\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(9) 
	public CKSConditionalOrderInitInsert LimitPrice(double LimitPrice) {
		this.io.setDoubleField(this, 9, LimitPrice);
		return this;
	}
	/**
	 * \ufffd\u06f8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSOrderPriceTypeType
	 */
	@Field(10) 
	public byte OrderPriceType() {
		return this.io.getByteField(this, 10);
	}
	/**
	 * \ufffd\u06f8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSOrderPriceTypeType
	 */
	@Field(10) 
	public CKSConditionalOrderInitInsert OrderPriceType(byte OrderPriceType) {
		this.io.setByteField(this, 10, OrderPriceType);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSConditionalTypeType
	 */
	@Field(11) 
	public byte ConditionalType() {
		return this.io.getByteField(this, 11);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSConditionalTypeType
	 */
	@Field(11) 
	public CKSConditionalOrderInitInsert ConditionalType(byte ConditionalType) {
		this.io.setByteField(this, 11, ConditionalType);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(12) 
	public double ConditionalPrice() {
		return this.io.getDoubleField(this, 12);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(12) 
	public CKSConditionalOrderInitInsert ConditionalPrice(double ConditionalPrice) {
		this.io.setDoubleField(this, 12, ConditionalPrice);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSConditionalOrderIDType
	 */
	@Field(13) 
	public int ConditionalOrderID() {
		return this.io.getIntField(this, 13);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSConditionalOrderIDType
	 */
	@Field(13) 
	public CKSConditionalOrderInitInsert ConditionalOrderID(int ConditionalOrderID) {
		this.io.setIntField(this, 13, ConditionalOrderID);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(14) 
	public int TriggeredTimes() {
		return this.io.getIntField(this, 14);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(14) 
	public CKSConditionalOrderInitInsert TriggeredTimes(int TriggeredTimes) {
		this.io.setIntField(this, 14, TriggeredTimes);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSConditionalOrderType
	 */
	@Field(15) 
	public byte OrderType() {
		return this.io.getByteField(this, 15);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSConditionalOrderType
	 */
	@Field(15) 
	public CKSConditionalOrderInitInsert OrderType(byte OrderType) {
		this.io.setByteField(this, 15, OrderType);
		return this;
	}
	/**
	 * \ufffd\ufffd\u0427\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(16) 
	public Pointer<Byte > ActiveTime() {
		return this.io.getPointerField(this, 16);
	}
	/**
	 * \u02a7\u0427\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(17) 
	public Pointer<Byte > InActiveTime() {
		return this.io.getPointerField(this, 17);
	}
	/**
	 * \ufffd\ufffd\ufffd\u04b4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({4}) 
	@Field(18) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 18);
	}
	public CKSConditionalOrderInitInsert(Pointer pointer) {
		super(pointer);
	}
}
