package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u01bd\ufffd\u05b2\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
 * <i>native declaration : KSVocApiStruct.h:731</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSCloseStrategyResultField extends StructObject {
	public CKSCloseStrategyResultField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeNameType
	 */
	@Array({61}) 
	@Field(1) 
	public Pointer<Byte > ExchangeName() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u01bd\ufffd\u05b2\ufffd\ufffd\ufffd<br>
	 * C type : TKSCloseStrategyType
	 */
	@Field(2) 
	public byte CloseStrategy() {
		return this.io.getByteField(this, 2);
	}
	/**
	 * \u01bd\ufffd\u05b2\ufffd\ufffd\ufffd<br>
	 * C type : TKSCloseStrategyType
	 */
	@Field(2) 
	public CKSCloseStrategyResultField CloseStrategy(byte CloseStrategy) {
		this.io.setByteField(this, 2, CloseStrategy);
		return this;
	}
	public CKSCloseStrategyResultField(Pointer pointer) {
		super(pointer);
	}
}
