package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\u03f2\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
 * <i>native declaration : KSVocApiStruct.h:759</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSCombStrategyResultField extends StructObject {
	public CKSCombStrategyResultField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0534\ufffd\ufffd\ufffd<br>
	 * C type : TKSStrategyIDType
	 */
	@Array({4}) 
	@Field(1) 
	public Pointer<Byte > StrategyID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSCombTypeType
	 */
	@Field(2) 
	public byte CombType() {
		return this.io.getByteField(this, 2);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSCombTypeType
	 */
	@Field(2) 
	public CKSCombStrategyResultField CombType(byte CombType) {
		this.io.setByteField(this, 2, CombType);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(3) 
	public byte CombDirection() {
		return this.io.getByteField(this, 3);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(3) 
	public CKSCombStrategyResultField CombDirection(byte CombDirection) {
		this.io.setByteField(this, 3, CombDirection);
		return this;
	}
	/**
	 * \ufffd\ufffd\u03ff\ufffd\u01bd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcCombOffsetFlagType
	 */
	@Array({5}) 
	@Field(4) 
	public Pointer<Byte > CombOffsetFlag() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(5) 
	public int Volume() {
		return this.io.getIntField(this, 5);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(5) 
	public CKSCombStrategyResultField Volume(int Volume) {
		this.io.setIntField(this, 5, Volume);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04bb<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(6) 
	public byte Direction1() {
		return this.io.getByteField(this, 6);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04bb<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(6) 
	public CKSCombStrategyResultField Direction1(byte Direction1) {
		this.io.setByteField(this, 6, Direction1);
		return this;
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be\u04bb<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(7) 
	public byte OffsetFlag1() {
		return this.io.getByteField(this, 7);
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be\u04bb<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(7) 
	public CKSCombStrategyResultField OffsetFlag1(byte OffsetFlag1) {
		this.io.setByteField(this, 7, OffsetFlag1);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04bb<br>
	 * C type : TThostFtdcVolRatioType
	 */
	@Field(8) 
	public double VolRatio1() {
		return this.io.getDoubleField(this, 8);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04bb<br>
	 * C type : TThostFtdcVolRatioType
	 */
	@Field(8) 
	public CKSCombStrategyResultField VolRatio1(double VolRatio1) {
		this.io.setDoubleField(this, 8, VolRatio1);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04bb<br>
	 * C type : TKSCalcFlagType
	 */
	@Field(9) 
	public byte CalcFlag1() {
		return this.io.getByteField(this, 9);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04bb<br>
	 * C type : TKSCalcFlagType
	 */
	@Field(9) 
	public CKSCombStrategyResultField CalcFlag1(byte CalcFlag1) {
		this.io.setByteField(this, 9, CalcFlag1);
		return this;
	}
	/**
	 * \ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\u04bb<br>
	 * C type : TThostFtdcMoneyRatioType
	 */
	@Field(10) 
	public double MarginRatio1() {
		return this.io.getDoubleField(this, 10);
	}
	/**
	 * \ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\u04bb<br>
	 * C type : TThostFtdcMoneyRatioType
	 */
	@Field(10) 
	public CKSCombStrategyResultField MarginRatio1(double MarginRatio1) {
		this.io.setDoubleField(this, 10, MarginRatio1);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(11) 
	public byte Direction2() {
		return this.io.getByteField(this, 11);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(11) 
	public CKSCombStrategyResultField Direction2(byte Direction2) {
		this.io.setByteField(this, 11, Direction2);
		return this;
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be\ufffd\ufffd<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(12) 
	public byte OffsetFlag2() {
		return this.io.getByteField(this, 12);
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be\ufffd\ufffd<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(12) 
	public CKSCombStrategyResultField OffsetFlag2(byte OffsetFlag2) {
		this.io.setByteField(this, 12, OffsetFlag2);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolRatioType
	 */
	@Field(13) 
	public double VolRatio2() {
		return this.io.getDoubleField(this, 13);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolRatioType
	 */
	@Field(13) 
	public CKSCombStrategyResultField VolRatio2(double VolRatio2) {
		this.io.setDoubleField(this, 13, VolRatio2);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u0176\ufffd<br>
	 * C type : TKSCalcFlagType
	 */
	@Field(14) 
	public byte CalcFlag2() {
		return this.io.getByteField(this, 14);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u0176\ufffd<br>
	 * C type : TKSCalcFlagType
	 */
	@Field(14) 
	public CKSCombStrategyResultField CalcFlag2(byte CalcFlag2) {
		this.io.setByteField(this, 14, CalcFlag2);
		return this;
	}
	/**
	 * \ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyRatioType
	 */
	@Field(15) 
	public double MarginRatio2() {
		return this.io.getDoubleField(this, 15);
	}
	/**
	 * \ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyRatioType
	 */
	@Field(15) 
	public CKSCombStrategyResultField MarginRatio2(double MarginRatio2) {
		this.io.setDoubleField(this, 15, MarginRatio2);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(16) 
	public byte Direction3() {
		return this.io.getByteField(this, 16);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(16) 
	public CKSCombStrategyResultField Direction3(byte Direction3) {
		this.io.setByteField(this, 16, Direction3);
		return this;
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be\ufffd\ufffd<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(17) 
	public byte OffsetFlag3() {
		return this.io.getByteField(this, 17);
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be\ufffd\ufffd<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(17) 
	public CKSCombStrategyResultField OffsetFlag3(byte OffsetFlag3) {
		this.io.setByteField(this, 17, OffsetFlag3);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolRatioType
	 */
	@Field(18) 
	public double VolRatio3() {
		return this.io.getDoubleField(this, 18);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolRatioType
	 */
	@Field(18) 
	public CKSCombStrategyResultField VolRatio3(double VolRatio3) {
		this.io.setDoubleField(this, 18, VolRatio3);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSCalcFlagType
	 */
	@Field(19) 
	public byte CalcFlag3() {
		return this.io.getByteField(this, 19);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSCalcFlagType
	 */
	@Field(19) 
	public CKSCombStrategyResultField CalcFlag3(byte CalcFlag3) {
		this.io.setByteField(this, 19, CalcFlag3);
		return this;
	}
	/**
	 * \ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyRatioType
	 */
	@Field(20) 
	public double MarginRatio3() {
		return this.io.getDoubleField(this, 20);
	}
	/**
	 * \ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyRatioType
	 */
	@Field(20) 
	public CKSCombStrategyResultField MarginRatio3(double MarginRatio3) {
		this.io.setDoubleField(this, 20, MarginRatio3);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(21) 
	public byte Direction4() {
		return this.io.getByteField(this, 21);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(21) 
	public CKSCombStrategyResultField Direction4(byte Direction4) {
		this.io.setByteField(this, 21, Direction4);
		return this;
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be\ufffd\ufffd<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(22) 
	public byte OffsetFlag4() {
		return this.io.getByteField(this, 22);
	}
	/**
	 * \ufffd\ufffd\u01bd\ufffd\ufffd\u05be\ufffd\ufffd<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(22) 
	public CKSCombStrategyResultField OffsetFlag4(byte OffsetFlag4) {
		this.io.setByteField(this, 22, OffsetFlag4);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolRatioType
	 */
	@Field(23) 
	public double VolRatio4() {
		return this.io.getDoubleField(this, 23);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolRatioType
	 */
	@Field(23) 
	public CKSCombStrategyResultField VolRatio4(double VolRatio4) {
		this.io.setDoubleField(this, 23, VolRatio4);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSCalcFlagType
	 */
	@Field(24) 
	public byte CalcFlag4() {
		return this.io.getByteField(this, 24);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSCalcFlagType
	 */
	@Field(24) 
	public CKSCombStrategyResultField CalcFlag4(byte CalcFlag4) {
		this.io.setByteField(this, 24, CalcFlag4);
		return this;
	}
	/**
	 * \ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyRatioType
	 */
	@Field(25) 
	public double MarginRatio4() {
		return this.io.getDoubleField(this, 25);
	}
	/**
	 * \ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyRatioType
	 */
	@Field(25) 
	public CKSCombStrategyResultField MarginRatio4(double MarginRatio4) {
		this.io.setDoubleField(this, 25, MarginRatio4);
		return this;
	}
	/**
	 * \ufffd\ufffd\u03fa\ufffd\u053c\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(26) 
	public Pointer<Byte > CombInstrumentID() {
		return this.io.getPointerField(this, 26);
	}
	public CKSCombStrategyResultField(Pointer pointer) {
		super(pointer);
	}
}
