package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\u02b7\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : KSVocApiStruct.h:1180</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSHistoryOrderField extends StructObject {
	public CKSHistoryOrderField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\u037b\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcIndividualNameType
	 */
	@Array({51}) 
	@Field(2) 
	public Pointer<Byte > CustomerName() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(3) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0631\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcOrderLocalIDType
	 */
	@Array({13}) 
	@Field(4) 
	public Pointer<Byte > OrderLocalID() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \ufffd\uac68\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(5) 
	public Pointer<Byte > InsertTime() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \u04b5\ufffd\ufffd\u052a<br>
	 * C type : TThostFtdcBusinessUnitType
	 */
	@Array({21}) 
	@Field(6) 
	public Pointer<Byte > BusinessUnit() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \ufffd\u027d\ufffd\ufffd\u06f8\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(7) 
	public double TradePrice() {
		return this.io.getDoubleField(this, 7);
	}
	/**
	 * \ufffd\u027d\ufffd\ufffd\u06f8\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(7) 
	public CKSHistoryOrderField TradePrice(double TradePrice) {
		this.io.setDoubleField(this, 7, TradePrice);
		return this;
	}
	/**
	 * \ufffd\u027d\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(8) 
	public double TradeAmount() {
		return this.io.getDoubleField(this, 8);
	}
	/**
	 * \ufffd\u027d\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(8) 
	public CKSHistoryOrderField TradeAmount(double TradeAmount) {
		this.io.setDoubleField(this, 8, TradeAmount);
		return this;
	}
	/**
	 * \ufffd\u027d\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(9) 
	public int VolumeTraded() {
		return this.io.getIntField(this, 9);
	}
	/**
	 * \ufffd\u027d\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(9) 
	public CKSHistoryOrderField VolumeTraded(int VolumeTraded) {
		this.io.setIntField(this, 9, VolumeTraded);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u2db3\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(10) 
	public double FrozenAmount() {
		return this.io.getDoubleField(this, 10);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u2db3\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(10) 
	public CKSHistoryOrderField FrozenAmount(double FrozenAmount) {
		this.io.setDoubleField(this, 10, FrozenAmount);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\u05b4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({4}) 
	@Field(11) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 11);
	}
	/**
	 * \ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(12) 
	public int SequenceNo() {
		return this.io.getIntField(this, 12);
	}
	/**
	 * \ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(12) 
	public CKSHistoryOrderField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 12, SequenceNo);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(13) 
	public byte Direction() {
		return this.io.getByteField(this, 13);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(13) 
	public CKSHistoryOrderField Direction(byte Direction) {
		this.io.setByteField(this, 13, Direction);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(14) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 14);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\u03e2<br>
	 * C type : TThostFtdcProductInfoType
	 */
	@Array({11}) 
	@Field(15) 
	public Pointer<Byte > UserProductInfo() {
		return this.io.getPointerField(this, 15);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(16) 
	public int RequestID() {
		return this.io.getIntField(this, 16);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(16) 
	public CKSHistoryOrderField RequestID(int RequestID) {
		this.io.setIntField(this, 16, RequestID);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({13}) 
	@Field(17) 
	public Pointer<Byte > OrderRef() {
		return this.io.getPointerField(this, 17);
	}
	/**
	 * \u01f0\ufffd\u00f1\ufffd\ufffd<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(18) 
	public int FrontID() {
		return this.io.getIntField(this, 18);
	}
	/**
	 * \u01f0\ufffd\u00f1\ufffd\ufffd<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(18) 
	public CKSHistoryOrderField FrontID(int FrontID) {
		this.io.setIntField(this, 18, FrontID);
		return this;
	}
	/**
	 * \ufffd\u1ef0\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(19) 
	public int SessionID() {
		return this.io.getIntField(this, 19);
	}
	/**
	 * \ufffd\u1ef0\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(19) 
	public CKSHistoryOrderField SessionID(int SessionID) {
		this.io.setIntField(this, 19, SessionID);
		return this;
	}
	/**
	 * \u03af\ufffd\u043c\u06f8\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(20) 
	public double OrderPrice() {
		return this.io.getDoubleField(this, 20);
	}
	/**
	 * \u03af\ufffd\u043c\u06f8\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(20) 
	public CKSHistoryOrderField OrderPrice(double OrderPrice) {
		this.io.setDoubleField(this, 20, OrderPrice);
		return this;
	}
	/**
	 * \u03af\ufffd\ufffd\ufffd\ufffd\u0534<br>
	 * C type : TThostFtdcOrderSourceType
	 */
	@Field(21) 
	public byte OrderSource() {
		return this.io.getByteField(this, 21);
	}
	/**
	 * \u03af\ufffd\ufffd\ufffd\ufffd\u0534<br>
	 * C type : TThostFtdcOrderSourceType
	 */
	@Field(21) 
	public CKSHistoryOrderField OrderSource(byte OrderSource) {
		this.io.setByteField(this, 21, OrderSource);
		return this;
	}
	/**
	 * \u03af\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({9}) 
	@Field(22) 
	public Pointer<Byte > InsertDate() {
		return this.io.getPointerField(this, 22);
	}
	/**
	 * \u03af\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(23) 
	public Pointer<Byte > OrderTime() {
		return this.io.getPointerField(this, 23);
	}
	/**
	 * \u03af\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(24) 
	public int VolumeTotalOriginal() {
		return this.io.getIntField(this, 24);
	}
	/**
	 * \u03af\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(24) 
	public CKSHistoryOrderField VolumeTotalOriginal(int VolumeTotalOriginal) {
		this.io.setIntField(this, 24, VolumeTotalOriginal);
		return this;
	}
	/**
	 * \u03af\ufffd\ufffd\u05f4\u032c<br>
	 * C type : TThostFtdcOrderStatusType
	 */
	@Field(25) 
	public byte OrderStatus() {
		return this.io.getByteField(this, 25);
	}
	/**
	 * \u03af\ufffd\ufffd\u05f4\u032c<br>
	 * C type : TThostFtdcOrderStatusType
	 */
	@Field(25) 
	public CKSHistoryOrderField OrderStatus(byte OrderStatus) {
		this.io.setByteField(this, 25, OrderStatus);
		return this;
	}
	/**
	 * \ufffd\ufffd\u01b7\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(26) 
	public Pointer<Byte > ProductID() {
		return this.io.getPointerField(this, 26);
	}
	/**
	 * \ufffd\ufffd\u01b7\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcProductNameType
	 */
	@Array({21}) 
	@Field(27) 
	public Pointer<Byte > ProductName() {
		return this.io.getPointerField(this, 27);
	}
	/**
	 * \ufffd\ufffd\u01b7\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcProductClassType
	 */
	@Field(28) 
	public byte ProductClass() {
		return this.io.getByteField(this, 28);
	}
	/**
	 * \ufffd\ufffd\u01b7\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcProductClassType
	 */
	@Field(28) 
	public CKSHistoryOrderField ProductClass(byte ProductClass) {
		this.io.setByteField(this, 28, ProductClass);
		return this;
	}
	/**
	 * \u04b5\ufffd\ufffd\ufffd\u05be<br>
	 * C type : TKSSOBusinessFlagType
	 */
	@Array({3}) 
	@Field(29) 
	public Pointer<Byte > BusinessFlag() {
		return this.io.getPointerField(this, 29);
	}
	/**
	 * \u04b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcFunctionNameType
	 */
	@Array({65}) 
	@Field(30) 
	public Pointer<Byte > FunctionName() {
		return this.io.getPointerField(this, 30);
	}
	public CKSHistoryOrderField(Pointer pointer) {
		super(pointer);
	}
}
