package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\u037b\ufffd\u00ff\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : KSVocApiStruct.h:1758</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSInputFundOutCreditApplyField extends StructObject {
	public CKSInputFundOutCreditApplyField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(2) 
	public double FundOutCredit() {
		return this.io.getDoubleField(this, 2);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(2) 
	public CKSInputFundOutCreditApplyField FundOutCredit(double FundOutCredit) {
		this.io.setDoubleField(this, 2, FundOutCredit);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\u0232\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSFOCreditApplyType
	 */
	@Field(3) 
	public byte CreditApplyFlag() {
		return this.io.getByteField(this, 3);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\u0232\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSFOCreditApplyType
	 */
	@Field(3) 
	public CKSInputFundOutCreditApplyField CreditApplyFlag(byte CreditApplyFlag) {
		this.io.setByteField(this, 3, CreditApplyFlag);
		return this;
	}
	/**
	 * \ufffd\ufffd\u02ee\ufffd\ufffd<br>
	 * C type : TThostFtdcTradeSerialNoType
	 */
	@Field(4) 
	public int CreditSerial() {
		return this.io.getIntField(this, 4);
	}
	/**
	 * \ufffd\ufffd\u02ee\ufffd\ufffd<br>
	 * C type : TThostFtdcTradeSerialNoType
	 */
	@Field(4) 
	public CKSInputFundOutCreditApplyField CreditSerial(int CreditSerial) {
		this.io.setIntField(this, 4, CreditSerial);
		return this;
	}
	public CKSInputFundOutCreditApplyField(Pointer pointer) {
		super(pointer);
	}
}
