package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\u0138\ufffd\ufffd\ufffd\ufffd\ufffd\u03f2\ufffd\ufffd<br>
 * <i>native declaration : KSVocApiStruct.h:1530</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSInputCombActionField extends StructObject {
	public CKSInputCombActionField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0534\ufffd\ufffd\ufffd<br>
	 * C type : TKSCombStrategyIDType
	 */
	@Array({9}) 
	@Field(2) 
	public Pointer<Byte > StrategyID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd1<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(3) 
	public Pointer<Byte > InstrumentID1() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd2<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(4) 
	public Pointer<Byte > InstrumentID2() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd3<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(5) 
	public Pointer<Byte > InstrumentID3() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd4<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(6) 
	public Pointer<Byte > InstrumentID4() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({13}) 
	@Field(7) 
	public Pointer<Byte > CombActionRef() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({16}) 
	@Field(8) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd1<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(9) 
	public byte Direction1() {
		return this.io.getByteField(this, 9);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd1<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(9) 
	public CKSInputCombActionField Direction1(byte Direction1) {
		this.io.setByteField(this, 9, Direction1);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd2<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(10) 
	public byte Direction2() {
		return this.io.getByteField(this, 10);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd2<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(10) 
	public CKSInputCombActionField Direction2(byte Direction2) {
		this.io.setByteField(this, 10, Direction2);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd3<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(11) 
	public byte Direction3() {
		return this.io.getByteField(this, 11);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd3<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(11) 
	public CKSInputCombActionField Direction3(byte Direction3) {
		this.io.setByteField(this, 11, Direction3);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd4<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(12) 
	public byte Direction4() {
		return this.io.getByteField(this, 12);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd4<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(12) 
	public CKSInputCombActionField Direction4(byte Direction4) {
		this.io.setByteField(this, 12, Direction4);
		return this;
	}
	/**
	 * \u01ff\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSCombActionType
	 */
	@Field(13) 
	public byte CombActionFlag() {
		return this.io.getByteField(this, 13);
	}
	/**
	 * \u01ff\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSCombActionType
	 */
	@Field(13) 
	public CKSInputCombActionField CombActionFlag(byte CombActionFlag) {
		this.io.setByteField(this, 13, CombActionFlag);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(14) 
	public int Volume() {
		return this.io.getIntField(this, 14);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(14) 
	public CKSInputCombActionField Volume(int Volume) {
		this.io.setIntField(this, 14, Volume);
		return this;
	}
	/**
	 * \ufffd\ufffd\u03f2\ufffd\u05b1\ufffd\ufffd<br>
	 * C type : TThostFtdcCombDirectionType
	 */
	@Field(15) 
	public byte CombDirection() {
		return this.io.getByteField(this, 15);
	}
	/**
	 * \ufffd\ufffd\u03f2\ufffd\u05b1\ufffd\ufffd<br>
	 * C type : TThostFtdcCombDirectionType
	 */
	@Field(15) 
	public CKSInputCombActionField CombDirection(byte CombDirection) {
		this.io.setByteField(this, 15, CombDirection);
		return this;
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u05f1\ufffd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(16) 
	public byte HedgeFlag() {
		return this.io.getByteField(this, 16);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u05f1\ufffd\ufffd\ufffd\u05be<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(16) 
	public CKSInputCombActionField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 16, HedgeFlag);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(17) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 17);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03f1\ufffd\ufffd<br>
	 * C type : TThostFtdcTradeIDType
	 */
	@Array({21}) 
	@Field(18) 
	public Pointer<Byte > ComTradeID() {
		return this.io.getPointerField(this, 18);
	}
	public CKSInputCombActionField(Pointer pointer) {
		super(pointer);
	}
}
