package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0524\u053c\ufffd\ufffd\u0221\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : KSVocApiStruct.h:1839</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSLargeFundOutApplyField extends StructObject {
	public CKSLargeFundOutApplyField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u0524\u053c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({9}) 
	@Field(2) 
	public Pointer<Byte > ApplyDate() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSFOCreditApplyType
	 */
	@Field(3) 
	public byte ApplyFlag() {
		return this.io.getByteField(this, 3);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSFOCreditApplyType
	 */
	@Field(3) 
	public CKSLargeFundOutApplyField ApplyFlag(byte ApplyFlag) {
		this.io.setByteField(this, 3, ApplyFlag);
		return this;
	}
	/**
	 * \ufffd\ufffd\u02ee\ufffd\ufffd<br>
	 * C type : TThostFtdcTradeSerialNoType
	 */
	@Field(4) 
	public int ApplySerial() {
		return this.io.getIntField(this, 4);
	}
	/**
	 * \ufffd\ufffd\u02ee\ufffd\ufffd<br>
	 * C type : TThostFtdcTradeSerialNoType
	 */
	@Field(4) 
	public CKSLargeFundOutApplyField ApplySerial(int ApplySerial) {
		this.io.setIntField(this, 4, ApplySerial);
		return this;
	}
	/**
	 * \u0524\u053c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5) 
	public double FundOutCredit() {
		return this.io.getDoubleField(this, 5);
	}
	/**
	 * \u0524\u053c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5) 
	public CKSLargeFundOutApplyField FundOutCredit(double FundOutCredit) {
		this.io.setDoubleField(this, 5, FundOutCredit);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\u05b4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({4}) 
	@Field(6) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0434\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBankIDType
	 */
	@Array({4}) 
	@Field(7) 
	public Pointer<Byte > BankID() {
		return this.io.getPointerField(this, 7);
	}
	public CKSLargeFundOutApplyField(Pointer pointer) {
		super(pointer);
	}
}
