package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u0228\ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd\u03f5\ufffd\ufffd<br>
 * <i>native declaration : KSVocApiStruct.h:579</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSOptionInstrGuardField extends StructObject {
	public CKSOptionInstrGuardField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(1) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(2) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\u0371\ufffd\ufffd\ufffd\u03f5\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(3) 
	public int MiniNumerator() {
		return this.io.getIntField(this, 3);
	}
	/**
	 * \ufffd\ufffd\u0371\ufffd\ufffd\ufffd\u03f5\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(3) 
	public CKSOptionInstrGuardField MiniNumerator(int MiniNumerator) {
		this.io.setIntField(this, 3, MiniNumerator);
		return this;
	}
	/**
	 * \ufffd\ufffd\u0371\ufffd\ufffd\ufffd\u03f5\ufffd\ufffd\ufffd\u0138<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(4) 
	public int MiniDenominator() {
		return this.io.getIntField(this, 4);
	}
	/**
	 * \ufffd\ufffd\u0371\ufffd\ufffd\ufffd\u03f5\ufffd\ufffd\ufffd\u0138<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(4) 
	public CKSOptionInstrGuardField MiniDenominator(int MiniDenominator) {
		this.io.setIntField(this, 4, MiniDenominator);
		return this;
	}
	/**
	 * \ufffd\ufffd\u0228\ufffd\ufffd\u053c\ufffd\ufffd\u0421\ufffd\ufffd\u05a4\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5) 
	public double MiniMargin() {
		return this.io.getDoubleField(this, 5);
	}
	/**
	 * \ufffd\ufffd\u0228\ufffd\ufffd\u053c\ufffd\ufffd\u0421\ufffd\ufffd\u05a4\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5) 
	public CKSOptionInstrGuardField MiniMargin(double MiniMargin) {
		this.io.setDoubleField(this, 5, MiniMargin);
		return this;
	}
	public CKSOptionInstrGuardField(Pointer pointer) {
		super(pointer);
	}
}
