package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u00bc\ufffd\ufffd\u05b9\ufffd\ufffd\u05b9\u04ef\ufffd\ufffd<br>
 * <i>native declaration : KSVocApiStruct.h:213</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSProfitAndLossOrderInsert extends StructObject {
	public CKSProfitAndLossOrderInsert() {
		super();
	}
	/**
	 * \u04ea\u04b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0631\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcOrderLocalIDType
	 */
	@Array({13}) 
	@Field(2) 
	public Pointer<Byte > OrderLocalID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u05b9\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(3) 
	public double StopLossPrice() {
		return this.io.getDoubleField(this, 3);
	}
	/**
	 * \u05b9\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(3) 
	public CKSProfitAndLossOrderInsert StopLossPrice(double StopLossPrice) {
		this.io.setDoubleField(this, 3, StopLossPrice);
		return this;
	}
	/**
	 * \u05b9\u04ef\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(4) 
	public double TakeProfitPrice() {
		return this.io.getDoubleField(this, 4);
	}
	/**
	 * \u05b9\u04ef\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(4) 
	public CKSProfitAndLossOrderInsert TakeProfitPrice(double TakeProfitPrice) {
		this.io.setDoubleField(this, 4, TakeProfitPrice);
		return this;
	}
	/**
	 * \u01bd\ufffd\u05b7\ufffd\u02bd<br>
	 * C type : TKSCloseModeType
	 */
	@Field(5) 
	public byte CloseMode() {
		return this.io.getByteField(this, 5);
	}
	/**
	 * \u01bd\ufffd\u05b7\ufffd\u02bd<br>
	 * C type : TKSCloseModeType
	 */
	@Field(5) 
	public CKSProfitAndLossOrderInsert CloseMode(byte CloseMode) {
		this.io.setByteField(this, 5, CloseMode);
		return this;
	}
	/**
	 * \u01bd\ufffd\u05b7\ufffd\ufffd\ufffd\u04fc\ufffd\ufffd\ufffd\u03bb\ufffd\ufffd\u01bd\ufffd\u05b7\ufffd\u02bd=1\ufffd\ufffd2\u02b1\ufffd\ufffd\u0427\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(6) 
	public double FiguresPrice() {
		return this.io.getDoubleField(this, 6);
	}
	/**
	 * \u01bd\ufffd\u05b7\ufffd\ufffd\ufffd\u04fc\ufffd\ufffd\ufffd\u03bb\ufffd\ufffd\u01bd\ufffd\u05b7\ufffd\u02bd=1\ufffd\ufffd2\u02b1\ufffd\ufffd\u0427\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(6) 
	public CKSProfitAndLossOrderInsert FiguresPrice(double FiguresPrice) {
		this.io.setDoubleField(this, 6, FiguresPrice);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(7) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \u04b5\ufffd\ufffd\u052a<br>
	 * C type : TThostFtdcBusinessUnitType
	 */
	@Array({21}) 
	@Field(8) 
	public Pointer<Byte > BusinessUnit() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * \ufffd\ufffd\ufffd\u04ef\ufffd\ufffd\u06f5\u0137\ufffd\u02bd<br>
	 * C type : TKSOffsetValueType
	 */
	@Field(9) 
	public byte OffsetValue() {
		return this.io.getByteField(this, 9);
	}
	/**
	 * \ufffd\ufffd\ufffd\u04ef\ufffd\ufffd\u06f5\u0137\ufffd\u02bd<br>
	 * C type : TKSOffsetValueType
	 */
	@Field(9) 
	public CKSProfitAndLossOrderInsert OffsetValue(byte OffsetValue) {
		this.io.setByteField(this, 9, OffsetValue);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06f8\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSSpringTypeType
	 */
	@Field(10) 
	public byte SpringType() {
		return this.io.getByteField(this, 10);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06f8\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSSpringTypeType
	 */
	@Field(10) 
	public CKSProfitAndLossOrderInsert SpringType(byte SpringType) {
		this.io.setByteField(this, 10, SpringType);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u05b9\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(11) 
	public double FloatLimitPrice() {
		return this.io.getDoubleField(this, 11);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u05b9\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(11) 
	public CKSProfitAndLossOrderInsert FloatLimitPrice(double FloatLimitPrice) {
		this.io.setDoubleField(this, 11, FloatLimitPrice);
		return this;
	}
	/**
	 * \u05b9\ufffd\ud896\udd74\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(12) 
	public int TriggeredTimes() {
		return this.io.getIntField(this, 12);
	}
	/**
	 * \u05b9\ufffd\ud896\udd74\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(12) 
	public CKSProfitAndLossOrderInsert TriggeredTimes(int TriggeredTimes) {
		this.io.setIntField(this, 12, TriggeredTimes);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\u04b4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({4}) 
	@Field(13) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 13);
	}
	/**
	 * \ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({81}) 
	@Field(14) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 14);
	}
	/**
	 * \u05b9\ufffd\ufffd\u05b9\u04ef\ufffd\ufffd\u05be<br>
	 * C type : TKSProfitAndLossFlagType
	 */
	@Field(15) 
	public byte ProfitAndLossFlag() {
		return this.io.getByteField(this, 15);
	}
	/**
	 * \u05b9\ufffd\ufffd\u05b9\u04ef\ufffd\ufffd\u05be<br>
	 * C type : TKSProfitAndLossFlagType
	 */
	@Field(15) 
	public CKSProfitAndLossOrderInsert ProfitAndLossFlag(byte ProfitAndLossFlag) {
		this.io.setByteField(this, 15, ProfitAndLossFlag);
		return this;
	}
	public CKSProfitAndLossOrderInsert(Pointer pointer) {
		super(pointer);
	}
}
