package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\u07b8\ufffd\u05b9\ufffd\ufffd\u05b9\u04ef\ufffd\ufffd<br>
 * <i>native declaration : KSVocApiStruct.h:284</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSProfitAndLossOrderModify extends StructObject {
	public CKSProfitAndLossOrderModify() {
		super();
	}
	/**
	 * \u04ea\u04b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u05b9\ufffd\ufffd\u05b9\u04ef\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSProfitAndLossOrderIDType
	 */
	@Field(2) 
	public int ProfitAndLossOrderID() {
		return this.io.getIntField(this, 2);
	}
	/**
	 * \u05b9\ufffd\ufffd\u05b9\u04ef\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSProfitAndLossOrderIDType
	 */
	@Field(2) 
	public CKSProfitAndLossOrderModify ProfitAndLossOrderID(int ProfitAndLossOrderID) {
		this.io.setIntField(this, 2, ProfitAndLossOrderID);
		return this;
	}
	/**
	 * \u05b9\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(3) 
	public double StopLossPrice() {
		return this.io.getDoubleField(this, 3);
	}
	/**
	 * \u05b9\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(3) 
	public CKSProfitAndLossOrderModify StopLossPrice(double StopLossPrice) {
		this.io.setDoubleField(this, 3, StopLossPrice);
		return this;
	}
	/**
	 * \u05b9\u04ef\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(4) 
	public double TakeProfitPrice() {
		return this.io.getDoubleField(this, 4);
	}
	/**
	 * \u05b9\u04ef\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(4) 
	public CKSProfitAndLossOrderModify TakeProfitPrice(double TakeProfitPrice) {
		this.io.setDoubleField(this, 4, TakeProfitPrice);
		return this;
	}
	/**
	 * \u01bd\ufffd\u05b7\ufffd\u02bd<br>
	 * C type : TKSCloseModeType
	 */
	@Field(5) 
	public byte CloseMode() {
		return this.io.getByteField(this, 5);
	}
	/**
	 * \u01bd\ufffd\u05b7\ufffd\u02bd<br>
	 * C type : TKSCloseModeType
	 */
	@Field(5) 
	public CKSProfitAndLossOrderModify CloseMode(byte CloseMode) {
		this.io.setByteField(this, 5, CloseMode);
		return this;
	}
	/**
	 * \u01bd\ufffd\u05b7\ufffd\ufffd\ufffd\ufffd\u03bb\ufffd\ufffd\u01bd\ufffd\u05b7\ufffd\u02bd=1\ufffd\ufffd2\u02b1\ufffd\ufffd\u0427\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(6) 
	public double FiguresPrice() {
		return this.io.getDoubleField(this, 6);
	}
	/**
	 * \u01bd\ufffd\u05b7\ufffd\ufffd\ufffd\ufffd\u03bb\ufffd\ufffd\u01bd\ufffd\u05b7\ufffd\u02bd=1\ufffd\ufffd2\u02b1\ufffd\ufffd\u0427\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(6) 
	public CKSProfitAndLossOrderModify FiguresPrice(double FiguresPrice) {
		this.io.setDoubleField(this, 6, FiguresPrice);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\u04ef\ufffd\ufffd\u06f5\u0137\ufffd\u02bd<br>
	 * C type : TKSOffsetValueType
	 */
	@Field(7) 
	public byte OffsetValue() {
		return this.io.getByteField(this, 7);
	}
	/**
	 * \ufffd\ufffd\ufffd\u04ef\ufffd\ufffd\u06f5\u0137\ufffd\u02bd<br>
	 * C type : TKSOffsetValueType
	 */
	@Field(7) 
	public CKSProfitAndLossOrderModify OffsetValue(byte OffsetValue) {
		this.io.setByteField(this, 7, OffsetValue);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06f8\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSSpringTypeType
	 */
	@Field(8) 
	public byte SpringType() {
		return this.io.getByteField(this, 8);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06f8\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TKSSpringTypeType
	 */
	@Field(8) 
	public CKSProfitAndLossOrderModify SpringType(byte SpringType) {
		this.io.setByteField(this, 8, SpringType);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u05b9\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(9) 
	public double FloatLimitPrice() {
		return this.io.getDoubleField(this, 9);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u05b9\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(9) 
	public CKSProfitAndLossOrderModify FloatLimitPrice(double FloatLimitPrice) {
		this.io.setDoubleField(this, 9, FloatLimitPrice);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(10) 
	public int TriggeredTimes() {
		return this.io.getIntField(this, 10);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(10) 
	public CKSProfitAndLossOrderModify TriggeredTimes(int TriggeredTimes) {
		this.io.setIntField(this, 10, TriggeredTimes);
		return this;
	}
	/**
	 * \u05b9\ufffd\ufffd\u05b9\u04ef\ufffd\ufffd\u05be<br>
	 * C type : TKSProfitAndLossFlagType
	 */
	@Field(11) 
	public byte ProfitAndLossFlag() {
		return this.io.getByteField(this, 11);
	}
	/**
	 * \u05b9\ufffd\ufffd\u05b9\u04ef\ufffd\ufffd\u05be<br>
	 * C type : TKSProfitAndLossFlagType
	 */
	@Field(11) 
	public CKSProfitAndLossOrderModify ProfitAndLossFlag(byte ProfitAndLossFlag) {
		this.io.setByteField(this, 11, ProfitAndLossFlag);
		return this;
	}
	public CKSProfitAndLossOrderModify(Pointer pointer) {
		super(pointer);
	}
}
