package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\ufffd\u04b5\ufffd\ufffd<br>
 * <i>native declaration : KSVocApiStruct.h:1460</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSPrimeDataBusinessField extends StructObject {
	public CKSPrimeDataBusinessField() {
		super();
	}
	/**
	 * \ufffd\u6d22\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcProcessNameType
	 */
	@Array({257}) 
	@Field(0) 
	public Pointer<Byte > ProcessName() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0737\ufffd\u02bd<br>
	 * C type : TThostFtdcFBTEncryModeType
	 */
	@Field(1) 
	public byte EncryMode() {
		return this.io.getByteField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0737\ufffd\u02bd<br>
	 * C type : TThostFtdcFBTEncryModeType
	 */
	@Field(1) 
	public CKSPrimeDataBusinessField EncryMode(byte EncryMode) {
		this.io.setByteField(this, 1, EncryMode);
		return this;
	}
	/**
	 * \ufffd\ufffd\u053f<br>
	 * C type : TThostFtdcPasswordKeyType
	 */
	@Array({129}) 
	@Field(2) 
	public Pointer<Byte > PasswordKey() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(3) 
	public int ErrorID() {
		return this.io.getIntField(this, 3);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(3) 
	public CKSPrimeDataBusinessField ErrorID(int ErrorID) {
		this.io.setIntField(this, 3, ErrorID);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : TThostFtdcErrorMsgType
	 */
	@Array({256}) 
	@Field(4) 
	public Pointer<Byte > ErrorMsg() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06b1\ufffd\u02b6\ufffd\ufffd\u01f0\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDescriptionType
	 */
	@Array({401}) 
	@Field(5) 
	public Pointer<Byte > AvailabeDescription() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \ufffd\ufffd\u077f\ufffd\ufffd\ufffd\u0775\u013d\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({9}) 
	@Field(6) 
	public Pointer<Byte > AvailabeTradingDay() {
		return this.io.getPointerField(this, 6);
	}
	public CKSPrimeDataBusinessField(Pointer pointer) {
		super(pointer);
	}
}
