package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\u037b\ufffd\u00ff\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u046f<br>
 * <i>native declaration : KSVocApiStruct.h:1816</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSRspQryFundOutCreditApplyField extends StructObject {
	public CKSRspQryFundOutCreditApplyField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\u02ee\ufffd\ufffd<br>
	 * C type : TThostFtdcTradeSerialNoType
	 */
	@Field(2) 
	public int CreditSerial() {
		return this.io.getIntField(this, 2);
	}
	/**
	 * \ufffd\ufffd\u02ee\ufffd\ufffd<br>
	 * C type : TThostFtdcTradeSerialNoType
	 */
	@Field(2) 
	public CKSRspQryFundOutCreditApplyField CreditSerial(int CreditSerial) {
		this.io.setIntField(this, 2, CreditSerial);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(3) 
	public double FundOutCredit() {
		return this.io.getDoubleField(this, 3);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(3) 
	public CKSRspQryFundOutCreditApplyField FundOutCredit(double FundOutCredit) {
		this.io.setDoubleField(this, 3, FundOutCredit);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\u0234\ufffd\ufffd\ufffd\u05f4\u032c<br>
	 * C type : TKSFOCreditStatusType
	 */
	@Field(4) 
	public byte DealStatus() {
		return this.io.getByteField(this, 4);
	}
	/**
	 * \ufffd\ufffd\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\u0234\ufffd\ufffd\ufffd\u05f4\u032c<br>
	 * C type : TKSFOCreditStatusType
	 */
	@Field(4) 
	public CKSRspQryFundOutCreditApplyField DealStatus(byte DealStatus) {
		this.io.setByteField(this, 4, DealStatus);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({9}) 
	@Field(5) 
	public Pointer<Byte > ApplyDate() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(6) 
	public Pointer<Byte > ApplyTime() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({9}) 
	@Field(7) 
	public Pointer<Byte > ConfirmDate() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(8) 
	public Pointer<Byte > ConfirmTime() {
		return this.io.getPointerField(this, 8);
	}
	public CKSRspQryFundOutCreditApplyField(Pointer pointer) {
		super(pointer);
	}
}
