package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\u046f\ufffd\u037b\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\u03e2\ufffd\ufffd\u04e6<br>
 * <i>native declaration : KSVocApiStruct.h:915</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSTransferInfoResultField extends StructObject {
	public CKSTransferInfoResultField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\u02bc\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > DepositBegin() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(1) 
	public Pointer<Byte > DepositEnd() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02bc\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(2) 
	public Pointer<Byte > WithdrawBegin() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > WithdrawEnd() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	@Field(4) 
	public double WithdrawVolume() {
		return this.io.getDoubleField(this, 4);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	@Field(4) 
	public CKSTransferInfoResultField WithdrawVolume(double WithdrawVolume) {
		this.io.setDoubleField(this, 4, WithdrawVolume);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u07b6\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5) 
	public double WithdrawLimit() {
		return this.io.getDoubleField(this, 5);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u07b6\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5) 
	public CKSTransferInfoResultField WithdrawLimit(double WithdrawLimit) {
		this.io.setDoubleField(this, 5, WithdrawLimit);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ud896\udd71\ufffd\ufffd\u07b6\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(6) 
	public double WithdrawLimitByTrade() {
		return this.io.getDoubleField(this, 6);
	}
	/**
	 * \ufffd\ufffd\ufffd\ud896\udd71\ufffd\ufffd\u07b6\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(6) 
	public CKSTransferInfoResultField WithdrawLimitByTrade(double WithdrawLimitByTrade) {
		this.io.setDoubleField(this, 6, WithdrawLimitByTrade);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(7) 
	public double Available() {
		return this.io.getDoubleField(this, 7);
	}
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(7) 
	public CKSTransferInfoResultField Available(double Available) {
		this.io.setDoubleField(this, 7, Available);
		return this;
	}
	/**
	 * \ufffd\u0473\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	@Field(8) 
	public double WithdrawedVolume() {
		return this.io.getDoubleField(this, 8);
	}
	/**
	 * \ufffd\u0473\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	@Field(8) 
	public CKSTransferInfoResultField WithdrawedVolume(double WithdrawedVolume) {
		this.io.setDoubleField(this, 8, WithdrawedVolume);
		return this;
	}
	/**
	 * \ufffd\u0473\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(9) 
	public double WithdrawedAmount() {
		return this.io.getDoubleField(this, 9);
	}
	/**
	 * \ufffd\u0473\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(9) 
	public CKSTransferInfoResultField WithdrawedAmount(double WithdrawedAmount) {
		this.io.setDoubleField(this, 9, WithdrawedAmount);
		return this;
	}
	/**
	 * \ufffd\ufffd\ufffd\u05b4\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({4}) 
	@Field(10) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 10);
	}
	public CKSTransferInfoResultField(Pointer pointer) {
		super(pointer);
	}
}
