package ksvocapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\u0534<br>
 * <i>native declaration : KSVocApiStruct.h:993</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiStruct") 
public class CKSUserProductUrlField extends StructObject {
	public CKSUserProductUrlField() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\u03e2<br>
	 * C type : TThostFtdcProductInfoType
	 */
	@Array({11}) 
	@Field(1) 
	public Pointer<Byte > UserProductInfo() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\ufffd\u00b0\u6c7e\ufffd\ufffd<br>
	 * C type : TKSProductVersionType
	 */
	@Array({21}) 
	@Field(2) 
	public Pointer<Byte > LastProductVersion() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0370\u6c7e\ufffd\ufffd<br>
	 * C type : TKSProductVersionType
	 */
	@Array({21}) 
	@Field(3) 
	public Pointer<Byte > MinUseProductVersion() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0370\u6c7e\ufffd\ufffd<br>
	 * C type : TKSProductVersionType
	 */
	@Array({21}) 
	@Field(4) 
	public Pointer<Byte > MinUpdateVersion() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\ufffd\u00b0\u6c7e\ufffd\ufffd\u05f0\ufffd\ufffd\ufffd\u0421<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	@Field(5) 
	public double InstallPackSize() {
		return this.io.getDoubleField(this, 5);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\ufffd\u00b0\u6c7e\ufffd\ufffd\u05f0\ufffd\ufffd\ufffd\u0421<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	@Field(5) 
	public CKSUserProductUrlField InstallPackSize(double InstallPackSize) {
		this.io.setDoubleField(this, 5, InstallPackSize);
		return this;
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\ufffd\u00b0\u6c7e\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : TThostFtdcTradeDateType
	 */
	@Array({9}) 
	@Field(6) 
	public Pointer<Byte > PublishDate() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\ufffd\u00b0\u6c7e\u02f5\ufffd\ufffd<br>
	 * C type : TThostFtdcUserProductMemoType
	 */
	@Array({129}) 
	@Field(7) 
	public Pointer<Byte > ProductMemo() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\u0534Url\ufffd\ufffd\u05b7<br>
	 * C type : TThostFtdcFunctionUrlType
	 */
	@Array({1025}) 
	@Field(8) 
	public Pointer<Byte > Url() {
		return this.io.getPointerField(this, 8);
	}
	public CKSUserProductUrlField(Pointer pointer) {
		super(pointer);
	}
}
