package ksvocapidatatype;
import java.util.Collections;
import java.util.Iterator;
import org.bridj.BridJ;
import org.bridj.FlagSet;
import org.bridj.IntValuedEnum;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
import org.bridj.cpp.CPPRuntime;
/**
 * Wrapper for library <b>KSVocApiDataType</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApiDataType") 
@Runtime(CPPRuntime.class) 
public class KSVocApiDataTypeLibrary {
	static {
		BridJ.register();
	}
	/**
	 * \ufffd\ufffd\u0771\ufffd\ufffd\u02b6\ufffd\ufffd\ufffd\ufffd<br>
	 * enum values<br>
	 * <i>native declaration : KSVocApiDataType.h:18</i>
	 */
	public enum KS_TABLEID_TYPE implements IntValuedEnum<KS_TABLEID_TYPE > {
		KS_DTI_Product(0),
		KS_DTI_Instrument(1),
		KS_DTI_DepthMarketData(2),
		KS_DTI_InstrumentRate(3),
		KS_DTI_TradingAccount(4),
		KS_DTI_InvestorPosition(5);
		KS_TABLEID_TYPE(long value) {
			this.value = value;
		}
		public final long value;
		public long value() {
			return this.value;
		}
		public Iterator<KS_TABLEID_TYPE > iterator() {
			return Collections.singleton(this).iterator();
		}
		public static IntValuedEnum<KS_TABLEID_TYPE > fromValue(int value) {
			return FlagSet.fromValue(value, values());
		}
	};
	/**
	 * \ufffd\ufffd\u0579API\ufffd\ufffd\ufffd\ufffd<br>
	 * enum values<br>
	 * <i>native declaration : KSVocApiDataType.h:29</i>
	 */
	public enum KS_EXTAPI_TYPE implements IntValuedEnum<KS_EXTAPI_TYPE > {
		KS_COS_API(0),
		KS_OPT_API(1),
		KS_VOC_API(2),
		KS_VOC_MDAPI(3),
		KS_PRD_API(4);
		KS_EXTAPI_TYPE(long value) {
			this.value = value;
		}
		public final long value;
		public long value() {
			return this.value;
		}
		public Iterator<KS_EXTAPI_TYPE > iterator() {
			return Collections.singleton(this).iterator();
		}
		public static IntValuedEnum<KS_EXTAPI_TYPE > fromValue(int value) {
			return FlagSet.fromValue(value, values());
		}
	};
	public static final int MAX_ORDER_COUNT = 20;
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_CallSettledRight = (String)"2f";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_ExecSettledDefaulted = (String)"2l";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_PutAssignedDuty = (String)"2d";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_ConfirmFlag_Confirmed = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderPrice_AskPrice = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_Select_SKIP = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_DisposalBack = (String)"2q";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_SellOpen = (String)"0f";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_SellClose = (String)"0e";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderPrice_BidPrice = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_TodayF_TIME = (char)'3';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_Select_AGAIN = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_CR_ALL = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_CoveredClose = (String)"0i";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_ConfirmFlag_UnConfirm = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_Select_ConfirmORCancel = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_TRIGGERTYPE_OPEN = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_ExecSettledDeal = (String)"2s";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_CoveredLock = (String)"2u";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_CombType_Swap = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_FOCAT_NoConfirm = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderStatus_WAITSELECT = (char)'6';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_CallAssignedDuty = (String)"2c";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_BuyOpen = (String)"0d";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_GreaterEqualTermPrice = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_LesserThanTermPrice = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_CR_Product = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_DutyPosition = (String)"2n";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderStatus_SENDSUCCESS = (char)'5';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_RightPosition = (String)"2m";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_CAT_True = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_CallSettledDuty_Covered = (String)"2j";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_EFMP_ITM_Include = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_PLF_ProfitAndLoss = (char)'3';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_PLF_Loss = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_PF_F = (char)'F';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_PF_D = (char)'D';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_PF_O = (char)'O';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_PF_T = (char)'T';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSPL_OffsetValue_TradePrice = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_DutyPosition_Covered = (String)"2o";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderPrice_LastPrice = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderStatus_ACTIVENOTOUCHED = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_CoveredOpen = (String)"0h";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KS_Select_AgainOrSkipOrAbort = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_ExecOrder = (String)"0j";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_FOCST_SENDING = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderStatus_SENDTIMEOUT = (char)'4';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSPL_SPRING_LastPrice = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSPL_Close_LastPrice = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_TRIGGERTYPE_QUOTAIONANDTIME = (char)'5';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_StrikePrice_Plus = (char)'N';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_EFMP_ITM_NotInclude = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_CAT_False = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderStatus_Deleted = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_OpenFCloseF_OrdiComb = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_SOPD_Sell = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_StrikePrice_Low = (char)'L';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_TL_Level1 = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_TL_Level2 = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_TL_Level3 = (char)'3';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderStatus_TOUCHEDNOSEND = (char)'3';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_PutAssignedRight = (String)"2b";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_Select_ABORT = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSPL_SPRING_SalePrice = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_SODM_Product = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSPL_Close_MarketPrice = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_TRIGGERTYPE_QUOTATION = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_DisposalOut = (String)"2p";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_StrikePrice_Minus = (char)'E';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_FOCST_ACCEPTED = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_State_ACTIVE = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_InfoType_Warn = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_InfoType_Common = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_InfoType_Force = (char)'5';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_OrdiComb_OpenFCloseF = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_BrokerAccountDeal = (String)"2t";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_ExecSettledDefault = (String)"2k";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_CallAssignedRight = (String)"2a";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_TRIGGERTYPE_TIME = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_StrikePrice_High = (char)'H';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_BuyClose = (String)"0g";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_InfoType_Roll = (char)'4';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_CalcFlag_Plus = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_PutSettledRight = (String)"2g";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_SOPD_Buy = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_ExecSettledRecv = (String)"2r";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSPL_OffsetValue_TermPrice = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderStatus_SELECTSKIP = (char)'7';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_FOCAT_Confirm = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderStatus_PAUSENOTOUCHED = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_CombType_Arbitrage = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_CallAssignedDuty_Covered = (String)"2e";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_InfoType_Risk = (char)'3';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_SODM_Cash = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_OrderStatus_SELECTABORT = (char)'8';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSPL_Close_SalePrice = (char)'1';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_State_PAUSE = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_PutSettledDuty = (String)"2i";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_PLF_Profit = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSCOS_PLF_NotProfitNotLoss = (char)'0';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_SODM_Dispos = (char)'3';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_FOCST_REJECT = (char)'2';
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final String KSVOC_SOOF_CallSettledDuty = (String)"2h";
	/// <i>native declaration : KSVocApiDataType.h</i>
	public static final char KSVOC_CalcFlag_Minus = (char)'2';
}
