package kstraderapiex;
import ksuserapidatatypeex.KSUserApiDataTypeExLibrary.THOST_TE_RESUME_TYPE;
import ksuserapistructex.CThostFtdcFensUserInfoField;
import ksuserapistructex.CThostFtdcInputCombActionField;
import ksuserapistructex.CThostFtdcInputExecOrderActionField;
import ksuserapistructex.CThostFtdcInputExecOrderField;
import ksuserapistructex.CThostFtdcInputForQuoteField;
import ksuserapistructex.CThostFtdcInputLockField;
import ksuserapistructex.CThostFtdcInputOrderActionField;
import ksuserapistructex.CThostFtdcInputOrderField;
import ksuserapistructex.CThostFtdcInputQuoteActionField;
import ksuserapistructex.CThostFtdcInputQuoteField;
import ksuserapistructex.CThostFtdcParkedOrderActionField;
import ksuserapistructex.CThostFtdcParkedOrderField;
import ksuserapistructex.CThostFtdcQryAccountregisterField;
import ksuserapistructex.CThostFtdcQryBrokerTradingAlgosField;
import ksuserapistructex.CThostFtdcQryBrokerTradingParamsField;
import ksuserapistructex.CThostFtdcQryCFMMCTradingAccountKeyField;
import ksuserapistructex.CThostFtdcQryCombActionField;
import ksuserapistructex.CThostFtdcQryCombInstrumentGuardField;
import ksuserapistructex.CThostFtdcQryContractBankField;
import ksuserapistructex.CThostFtdcQryDepthMarketDataField;
import ksuserapistructex.CThostFtdcQryEWarrantOffsetField;
import ksuserapistructex.CThostFtdcQryExchangeField;
import ksuserapistructex.CThostFtdcQryExchangeMarginRateAdjustField;
import ksuserapistructex.CThostFtdcQryExchangeMarginRateField;
import ksuserapistructex.CThostFtdcQryExchangeRateField;
import ksuserapistructex.CThostFtdcQryExecOrderField;
import ksuserapistructex.CThostFtdcQryForQuoteField;
import ksuserapistructex.CThostFtdcQryInstrumentCommissionRateField;
import ksuserapistructex.CThostFtdcQryInstrumentField;
import ksuserapistructex.CThostFtdcQryInstrumentMarginRateField;
import ksuserapistructex.CThostFtdcQryInstrumentOrderCommRateField;
import ksuserapistructex.CThostFtdcQryInvestorField;
import ksuserapistructex.CThostFtdcQryInvestorPositionCombineDetailField;
import ksuserapistructex.CThostFtdcQryInvestorPositionDetailField;
import ksuserapistructex.CThostFtdcQryInvestorPositionField;
import ksuserapistructex.CThostFtdcQryInvestorProductGroupMarginField;
import ksuserapistructex.CThostFtdcQryLockField;
import ksuserapistructex.CThostFtdcQryLockPositionField;
import ksuserapistructex.CThostFtdcQryNoticeField;
import ksuserapistructex.CThostFtdcQryOptionInstrCommRateField;
import ksuserapistructex.CThostFtdcQryOptionInstrTradeCostField;
import ksuserapistructex.CThostFtdcQryOrderField;
import ksuserapistructex.CThostFtdcQryParkedOrderActionField;
import ksuserapistructex.CThostFtdcQryParkedOrderField;
import ksuserapistructex.CThostFtdcQryProductExchRateField;
import ksuserapistructex.CThostFtdcQryProductField;
import ksuserapistructex.CThostFtdcQryProductGroupField;
import ksuserapistructex.CThostFtdcQryQuoteField;
import ksuserapistructex.CThostFtdcQrySecAgentACIDMapField;
import ksuserapistructex.CThostFtdcQrySettlementInfoConfirmField;
import ksuserapistructex.CThostFtdcQrySettlementInfoField;
import ksuserapistructex.CThostFtdcQryTradeField;
import ksuserapistructex.CThostFtdcQryTradingAccountField;
import ksuserapistructex.CThostFtdcQryTradingCodeField;
import ksuserapistructex.CThostFtdcQryTradingNoticeField;
import ksuserapistructex.CThostFtdcQryTransferBankField;
import ksuserapistructex.CThostFtdcQryTransferSerialField;
import ksuserapistructex.CThostFtdcQueryCFMMCTradingAccountTokenField;
import ksuserapistructex.CThostFtdcQueryMaxOrderVolumeField;
import ksuserapistructex.CThostFtdcRemoveParkedOrderActionField;
import ksuserapistructex.CThostFtdcRemoveParkedOrderField;
import ksuserapistructex.CThostFtdcReqAuthenticateField;
import ksuserapistructex.CThostFtdcReqQueryAccountField;
import ksuserapistructex.CThostFtdcReqTransferField;
import ksuserapistructex.CThostFtdcReqUserLoginField;
import ksuserapistructex.CThostFtdcSettlementInfoConfirmField;
import ksuserapistructex.CThostFtdcTradingAccountPasswordUpdateField;
import ksuserapistructex.CThostFtdcUserLogoutField;
import ksuserapistructex.CThostFtdcUserPasswordUpdateField;
import ksvocapidatatype.KSVocApiDataTypeLibrary.KS_EXTAPI_TYPE;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Virtual;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : KSTraderApiEx.h:374</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSTraderApiEx") 
public class CThostFtdcTraderApi extends CPPObject {
	public CThostFtdcTraderApi() {
		super();
	}
	/**
	 * @return \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdUserApi<br>
	 * Original signature : <code>CThostFtdcTraderApi* CreateFtdcTraderApi(const char*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:380</i>
	 */
	public static native Pointer<CThostFtdcTraderApi > CreateFtdcTraderApi(Pointer<Byte > pszFlowPath);
	/**
	 * @retrun \ufffd\ufffd\u0221\ufffd\ufffd\ufffd\u0130\u6c7e\ufffd\ufffd<br>
	 * Original signature : <code>char* GetApiVersion()</code><br>
	 * <i>native declaration : KSTraderApiEx.h:384</i>
	 */
	public static native Pointer<Byte > GetApiVersion();
	/**
	 * @remark \ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\u00f1\ufffd\ufffd\u04ff\u06b6\ufffd\ufffd\ufffd\u02b1,\ufffd\ufffd\ufffd\u00f8\u00fa\ufffd\ufffd\ufffd\u027e\ufffd\ufffd\u04ff\u06b6\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>void Release()</code><br>
	 * <i>native declaration : KSTraderApiEx.h:388</i>
	 */
	@Virtual(0) 
	public native void Release();
	/**
	 * @remark \ufffd\ufffd\u02bc\ufffd\ufffd\ufffd\ufffd\ufffd\u043b\ufffd\ufffd\ufffd,\u05bb\ufffd\u0435\ufffd\ufffd\u00fa\ufffd,\ufffd\u04ff\u06b2\u017f\ufffd\u02bc\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>void Init()</code><br>
	 * <i>native declaration : KSTraderApiEx.h:392</i>
	 */
	@Virtual(1) 
	public native void Init();
	/**
	 * @return \ufffd\u07f3\ufffd\ufffd\u02f3\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int Join()</code><br>
	 * <i>native declaration : KSTraderApiEx.h:396</i>
	 */
	@Virtual(2) 
	public native int Join();
	/**
	 * @remark \u05bb\ufffd\u0435\ufffd\u00bc\ufffd\u0279\ufffd\ufffd\ufffd,\ufffd\ufffd\ufffd\u0735\u00f5\ufffd\ufffd\ufffd\u0237\ufffd\u013d\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>char* GetTradingDay()</code><br>
	 * <i>native declaration : KSTraderApiEx.h:401</i>
	 */
	@Virtual(3) 
	public native Pointer<Byte > GetTradingDay();
	/**
	 * @remark \ufffd\ufffdtcp\ufffd\ufffd\ufffd\ufffd\udd2b\ufffd\ufffd\u042d\ufffd\u98ec\ufffd\ufffd127.0.0.1\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05b7\ufffd\ufffd\ufffd\ufffd17001\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02ff\u06ba\u0161\ufffd<br>
	 * Original signature : <code>void RegisterFront(char*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:407</i>
	 */
	@Virtual(4) 
	public native void RegisterFront(Pointer<Byte > pszFrontAddress);
	/**
	 * @remark RegisterNameServer\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdRegisterFront<br>
	 * Original signature : <code>void RegisterNameServer(char*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:414</i>
	 */
	@Virtual(5) 
	public native void RegisterNameServer(Pointer<Byte > pszNsAddress);
	/**
	 * @param pFensUserInfo\ufffd\ufffd\ufffd\u00fb\ufffd\ufffd\ufffd\u03e2\ufffd\ufffd<br>
	 * Original signature : <code>void RegisterFensUserInfo(CThostFtdcFensUserInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:418</i>
	 */
	@Virtual(6) 
	public native void RegisterFensUserInfo(Pointer<CThostFtdcFensUserInfoField > pFensUserInfo);
	/**
	 * @param pSpi \ufffd\ufffd\ufffd\ufffd\ufffd\u053b\u0635\ufffd\ufffd\u04ff\ufffd\ufffd\ufffd\ufffd\u02b5\ufffd\ufffd<br>
	 * Original signature : <code>void RegisterSpi(CThostFtdcTraderSpi*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:422</i>
	 */
	@Virtual(7) 
	public native void RegisterSpi(Pointer<CThostFtdcTraderSpi > pSpi);
	/**
	 * @remark \ufffd\u00f7\ufffd\ufffd\ufffd\u04aa\ufffd\ufffdInit\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\ufffd\ufffd\u00e1\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\uda8b\udefb\ufffd\ufffd\u0575\ufffd\u02fd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0761\ufffd<br>
	 * Original signature : <code>void SubscribePrivateTopic(THOST_TE_RESUME_TYPE)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:430</i>
	 */
	@Virtual(8) 
	public native void SubscribePrivateTopic(IntValuedEnum<THOST_TE_RESUME_TYPE > nResumeType);
	/**
	 * @remark \ufffd\u00f7\ufffd\ufffd\ufffd\u04aa\ufffd\ufffdInit\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\ufffd\ufffd\u00e1\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\uda8b\udefb\ufffd\ufffd\u0575\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0761\ufffd<br>
	 * Original signature : <code>void SubscribePublicTopic(THOST_TE_RESUME_TYPE)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:438</i>
	 */
	@Virtual(9) 
	public native void SubscribePublicTopic(IntValuedEnum<THOST_TE_RESUME_TYPE > nResumeType);
	/**
	 * \ufffd\u037b\ufffd\ufffd\ufffd\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqAuthenticate(CThostFtdcReqAuthenticateField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:441</i>
	 */
	@Virtual(10) 
	public native int ReqAuthenticate(Pointer<CThostFtdcReqAuthenticateField > pReqAuthenticateField, int nRequestID);
	/**
	 * \ufffd\u00fb\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqUserLogin(CThostFtdcReqUserLoginField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:444</i>
	 */
	@Virtual(11) 
	public native int ReqUserLogin(Pointer<CThostFtdcReqUserLoginField > pReqUserLoginField, int nRequestID);
	/**
	 * \ufffd\u01f3\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqUserLogout(CThostFtdcUserLogoutField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:447</i>
	 */
	@Virtual(12) 
	public native int ReqUserLogout(Pointer<CThostFtdcUserLogoutField > pUserLogout, int nRequestID);
	/**
	 * \ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqUserPasswordUpdate(CThostFtdcUserPasswordUpdateField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:450</i>
	 */
	@Virtual(13) 
	public native int ReqUserPasswordUpdate(Pointer<CThostFtdcUserPasswordUpdateField > pUserPasswordUpdate, int nRequestID);
	/**
	 * \ufffd\u02bd\ufffd\ufffd\u02fb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqTradingAccountPasswordUpdate(CThostFtdcTradingAccountPasswordUpdateField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:453</i>
	 */
	@Virtual(14) 
	public native int ReqTradingAccountPasswordUpdate(Pointer<CThostFtdcTradingAccountPasswordUpdateField > pTradingAccountPasswordUpdate, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqOrderInsert(CThostFtdcInputOrderField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:456</i>
	 */
	@Virtual(15) 
	public native int ReqOrderInsert(Pointer<CThostFtdcInputOrderField > pInputOrder, int nRequestID);
	/**
	 * \u0524\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqParkedOrderInsert(CThostFtdcParkedOrderField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:459</i>
	 */
	@Virtual(16) 
	public native int ReqParkedOrderInsert(Pointer<CThostFtdcParkedOrderField > pParkedOrder, int nRequestID);
	/**
	 * \u0524\ufffd\ud98f\uddf5\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqParkedOrderAction(CThostFtdcParkedOrderActionField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:462</i>
	 */
	@Virtual(17) 
	public native int ReqParkedOrderAction(Pointer<CThostFtdcParkedOrderActionField > pParkedOrderAction, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqOrderAction(CThostFtdcInputOrderActionField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:465</i>
	 */
	@Virtual(18) 
	public native int ReqOrderAction(Pointer<CThostFtdcInputOrderActionField > pInputOrderAction, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\udb86\ude35\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQueryMaxOrderVolume(CThostFtdcQueryMaxOrderVolumeField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:468</i>
	 */
	@Virtual(19) 
	public native int ReqQueryMaxOrderVolume(Pointer<CThostFtdcQueryMaxOrderVolumeField > pQueryMaxOrderVolume, int nRequestID);
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07fd\ufffd\ufffd\ufffd\ufffd\ufffd\u0237\ufffd\ufffd<br>
	 * Original signature : <code>int ReqSettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:471</i>
	 */
	@Virtual(20) 
	public native int ReqSettlementInfoConfirm(Pointer<CThostFtdcSettlementInfoConfirmField > pSettlementInfoConfirm, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u027e\ufffd\ufffd\u0524\ufffd\ufffd<br>
	 * Original signature : <code>int ReqRemoveParkedOrder(CThostFtdcRemoveParkedOrderField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:474</i>
	 */
	@Virtual(21) 
	public native int ReqRemoveParkedOrder(Pointer<CThostFtdcRemoveParkedOrderField > pRemoveParkedOrder, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u027e\ufffd\ufffd\u0524\ufffd\ud98f\uddf5\ufffd<br>
	 * Original signature : <code>int ReqRemoveParkedOrderAction(CThostFtdcRemoveParkedOrderActionField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:477</i>
	 */
	@Virtual(22) 
	public native int ReqRemoveParkedOrderAction(Pointer<CThostFtdcRemoveParkedOrderActionField > pRemoveParkedOrderAction, int nRequestID);
	/**
	 * \u05b4\ufffd\ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqExecOrderInsert(CThostFtdcInputExecOrderField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:480</i>
	 */
	@Virtual(23) 
	public native int ReqExecOrderInsert(Pointer<CThostFtdcInputExecOrderField > pInputExecOrder, int nRequestID);
	/**
	 * \u05b4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqExecOrderAction(CThostFtdcInputExecOrderActionField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:483</i>
	 */
	@Virtual(24) 
	public native int ReqExecOrderAction(Pointer<CThostFtdcInputExecOrderActionField > pInputExecOrderAction, int nRequestID);
	/**
	 * \u046f\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqForQuoteInsert(CThostFtdcInputForQuoteField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:486</i>
	 */
	@Virtual(25) 
	public native int ReqForQuoteInsert(Pointer<CThostFtdcInputForQuoteField > pInputForQuote, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQuoteInsert(CThostFtdcInputQuoteField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:489</i>
	 */
	@Virtual(26) 
	public native int ReqQuoteInsert(Pointer<CThostFtdcInputQuoteField > pInputQuote, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\u06f2\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQuoteAction(CThostFtdcInputQuoteActionField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:492</i>
	 */
	@Virtual(27) 
	public native int ReqQuoteAction(Pointer<CThostFtdcInputQuoteActionField > pInputQuoteAction, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqLockInsert(CThostFtdcInputLockField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:495</i>
	 */
	@Virtual(28) 
	public native int ReqLockInsert(Pointer<CThostFtdcInputLockField > pInputLock, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqCombActionInsert(CThostFtdcInputCombActionField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:498</i>
	 */
	@Virtual(29) 
	public native int ReqCombActionInsert(Pointer<CThostFtdcInputCombActionField > pInputCombAction, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryOrder(CThostFtdcQryOrderField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:501</i>
	 */
	@Virtual(30) 
	public native int ReqQryOrder(Pointer<CThostFtdcQryOrderField > pQryOrder, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\u027d\ufffd<br>
	 * Original signature : <code>int ReqQryTrade(CThostFtdcQryTradeField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:504</i>
	 */
	@Virtual(31) 
	public native int ReqQryTrade(Pointer<CThostFtdcQryTradeField > pQryTrade, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\u07f3\u05b2\ufffd<br>
	 * Original signature : <code>int ReqQryInvestorPosition(CThostFtdcQryInvestorPositionField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:507</i>
	 */
	@Virtual(32) 
	public native int ReqQryInvestorPosition(Pointer<CThostFtdcQryInvestorPositionField > pQryInvestorPosition, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\u02bd\ufffd\ufffd\u02fb\ufffd<br>
	 * Original signature : <code>int ReqQryTradingAccount(CThostFtdcQryTradingAccountField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:510</i>
	 */
	@Virtual(33) 
	public native int ReqQryTradingAccount(Pointer<CThostFtdcQryTradingAccountField > pQryTradingAccount, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryInvestor(CThostFtdcQryInvestorField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:513</i>
	 */
	@Virtual(34) 
	public native int ReqQryInvestor(Pointer<CThostFtdcQryInvestorField > pQryInvestor, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\u05f1\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryTradingCode(CThostFtdcQryTradingCodeField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:516</i>
	 */
	@Virtual(35) 
	public native int ReqQryTradingCode(Pointer<CThostFtdcQryTradingCodeField > pQryTradingCode, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u053c\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryInstrumentMarginRate(CThostFtdcQryInstrumentMarginRateField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:519</i>
	 */
	@Virtual(36) 
	public native int ReqQryInstrumentMarginRate(Pointer<CThostFtdcQryInstrumentMarginRateField > pQryInstrumentMarginRate, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryInstrumentCommissionRate(CThostFtdcQryInstrumentCommissionRateField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:522</i>
	 */
	@Virtual(37) 
	public native int ReqQryInstrumentCommissionRate(Pointer<CThostFtdcQryInstrumentCommissionRateField > pQryInstrumentCommissionRate, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryExchange(CThostFtdcQryExchangeField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:525</i>
	 */
	@Virtual(38) 
	public native int ReqQryExchange(Pointer<CThostFtdcQryExchangeField > pQryExchange, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u01b7<br>
	 * Original signature : <code>int ReqQryProduct(CThostFtdcQryProductField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:528</i>
	 */
	@Virtual(39) 
	public native int ReqQryProduct(Pointer<CThostFtdcQryProductField > pQryProduct, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u053c<br>
	 * Original signature : <code>int ReqQryInstrument(CThostFtdcQryInstrumentField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:531</i>
	 */
	@Virtual(40) 
	public native int ReqQryInstrument(Pointer<CThostFtdcQryInstrumentField > pQryInstrument, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryDepthMarketData(CThostFtdcQryDepthMarketDataField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:534</i>
	 */
	@Virtual(41) 
	public native int ReqQryDepthMarketData(Pointer<CThostFtdcQryDepthMarketDataField > pQryDepthMarketData, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\u07fd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQrySettlementInfo(CThostFtdcQrySettlementInfoField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:537</i>
	 */
	@Virtual(42) 
	public native int ReqQrySettlementInfo(Pointer<CThostFtdcQrySettlementInfoField > pQrySettlementInfo, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryTransferBank(CThostFtdcQryTransferBankField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:540</i>
	 */
	@Virtual(43) 
	public native int ReqQryTransferBank(Pointer<CThostFtdcQryTransferBankField > pQryTransferBank, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\u07f3\u05b2\ufffd\ufffd\ufffd\u03f8<br>
	 * Original signature : <code>int ReqQryInvestorPositionDetail(CThostFtdcQryInvestorPositionDetailField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:543</i>
	 */
	@Virtual(44) 
	public native int ReqQryInvestorPositionDetail(Pointer<CThostFtdcQryInvestorPositionDetailField > pQryInvestorPositionDetail, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\u037b\ufffd\u0368\u05aa<br>
	 * Original signature : <code>int ReqQryNotice(CThostFtdcQryNoticeField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:546</i>
	 */
	@Virtual(45) 
	public native int ReqQryNotice(Pointer<CThostFtdcQryNoticeField > pQryNotice, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2\u0237\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQrySettlementInfoConfirm(CThostFtdcQrySettlementInfoConfirmField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:549</i>
	 */
	@Virtual(46) 
	public native int ReqQrySettlementInfoConfirm(Pointer<CThostFtdcQrySettlementInfoConfirmField > pQrySettlementInfoConfirm, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\u07f3\u05b2\ufffd\ufffd\ufffd\u03f8<br>
	 * Original signature : <code>int ReqQryInvestorPositionCombineDetail(CThostFtdcQryInvestorPositionCombineDetailField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:552</i>
	 */
	@Virtual(47) 
	public native int ReqQryInvestorPositionCombineDetail(Pointer<CThostFtdcQryInvestorPositionCombineDetailField > pQryInvestorPositionCombineDetail, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\u03f5\u0373\ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\u02bd\ufffd\ufffd\u02fb\ufffd\ufffd\ufffd\u053f<br>
	 * Original signature : <code>int ReqQryCFMMCTradingAccountKey(CThostFtdcQryCFMMCTradingAccountKeyField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:555</i>
	 */
	@Virtual(48) 
	public native int ReqQryCFMMCTradingAccountKey(Pointer<CThostFtdcQryCFMMCTradingAccountKeyField > pQryCFMMCTradingAccountKey, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\u05b5\ufffd\ufffd\u06f5\ufffd\ufffd\ufffd\u03e2<br>
	 * Original signature : <code>int ReqQryEWarrantOffset(CThostFtdcQryEWarrantOffsetField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:558</i>
	 */
	@Virtual(49) 
	public native int ReqQryEWarrantOffset(Pointer<CThostFtdcQryEWarrantOffsetField > pQryEWarrantOffset, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\ufffd\u01b7\ufffd\ufffd/\ufffd\ufffd\u01b7\ufffd\u05b1\ufffd\u05a4\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryInvestorProductGroupMargin(CThostFtdcQryInvestorProductGroupMarginField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:561</i>
	 */
	@Virtual(50) 
	public native int ReqQryInvestorProductGroupMargin(Pointer<CThostFtdcQryInvestorProductGroupMarginField > pQryInvestorProductGroupMargin, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryExchangeMarginRate(CThostFtdcQryExchangeMarginRateField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:564</i>
	 */
	@Virtual(51) 
	public native int ReqQryExchangeMarginRate(Pointer<CThostFtdcQryExchangeMarginRateField > pQryExchangeMarginRate, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryExchangeMarginRateAdjust(CThostFtdcQryExchangeMarginRateAdjustField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:567</i>
	 */
	@Virtual(52) 
	public native int ReqQryExchangeMarginRateAdjust(Pointer<CThostFtdcQryExchangeMarginRateAdjustField > pQryExchangeMarginRateAdjust, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryExchangeRate(CThostFtdcQryExchangeRateField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:570</i>
	 */
	@Virtual(53) 
	public native int ReqQryExchangeRate(Pointer<CThostFtdcQryExchangeRateField > pQryExchangeRate, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0531\ufffd\ufffd\ufffd\ufffd\u0228\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQrySecAgentACIDMap(CThostFtdcQrySecAgentACIDMapField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:573</i>
	 */
	@Virtual(54) 
	public native int ReqQrySecAgentACIDMap(Pointer<CThostFtdcQrySecAgentACIDMapField > pQrySecAgentACIDMap, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u01b7\ufffd\ufffd\ufffd\u06fb\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryProductExchRate(CThostFtdcQryProductExchRateField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:576</i>
	 */
	@Virtual(55) 
	public native int ReqQryProductExchRate(Pointer<CThostFtdcQryProductExchRateField > pQryProductExchRate, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u01b7\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryProductGroup(CThostFtdcQryProductGroupField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:579</i>
	 */
	@Virtual(56) 
	public native int ReqQryProductGroup(Pointer<CThostFtdcQryProductGroupField > pQryProductGroup, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryInstrumentOrderCommRate(CThostFtdcQryInstrumentOrderCommRateField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:582</i>
	 */
	@Virtual(57) 
	public native int ReqQryInstrumentOrderCommRate(Pointer<CThostFtdcQryInstrumentOrderCommRateField > pQryInstrumentOrderCommRate, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u0228\ufffd\ufffd\ufffd\u05f3\u0271\ufffd<br>
	 * Original signature : <code>int ReqQryOptionInstrTradeCost(CThostFtdcQryOptionInstrTradeCostField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:585</i>
	 */
	@Virtual(58) 
	public native int ReqQryOptionInstrTradeCost(Pointer<CThostFtdcQryOptionInstrTradeCostField > pQryOptionInstrTradeCost, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u0228\ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryOptionInstrCommRate(CThostFtdcQryOptionInstrCommRateField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:588</i>
	 */
	@Virtual(59) 
	public native int ReqQryOptionInstrCommRate(Pointer<CThostFtdcQryOptionInstrCommRateField > pQryOptionInstrCommRate, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u05b4\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryExecOrder(CThostFtdcQryExecOrderField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:591</i>
	 */
	@Virtual(60) 
	public native int ReqQryExecOrder(Pointer<CThostFtdcQryExecOrderField > pQryExecOrder, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u046f\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryForQuote(CThostFtdcQryForQuoteField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:594</i>
	 */
	@Virtual(61) 
	public native int ReqQryForQuote(Pointer<CThostFtdcQryForQuoteField > pQryForQuote, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryQuote(CThostFtdcQryQuoteField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:597</i>
	 */
	@Virtual(62) 
	public native int ReqQryQuote(Pointer<CThostFtdcQryQuoteField > pQryQuote, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryLock(CThostFtdcQryLockField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:600</i>
	 */
	@Virtual(63) 
	public native int ReqQryLock(Pointer<CThostFtdcQryLockField > pQryLock, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u05a4\u022f\ufffd\ufffd\u03bb<br>
	 * Original signature : <code>int ReqQryLockPosition(CThostFtdcQryLockPositionField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:603</i>
	 */
	@Virtual(64) 
	public native int ReqQryLockPosition(Pointer<CThostFtdcQryLockPositionField > pQryLockPosition, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u03fa\ufffd\u053c\ufffd\ufffd\u022b\u03f5\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryCombInstrumentGuard(CThostFtdcQryCombInstrumentGuardField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:606</i>
	 */
	@Virtual(65) 
	public native int ReqQryCombInstrumentGuard(Pointer<CThostFtdcQryCombInstrumentGuardField > pQryCombInstrumentGuard, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryCombAction(CThostFtdcQryCombActionField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:609</i>
	 */
	@Virtual(66) 
	public native int ReqQryCombAction(Pointer<CThostFtdcQryCombActionField > pQryCombAction, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u05ea\ufffd\ufffd\ufffd\ufffd\u02ee<br>
	 * Original signature : <code>int ReqQryTransferSerial(CThostFtdcQryTransferSerialField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:612</i>
	 */
	@Virtual(67) 
	public native int ReqQryTransferSerial(Pointer<CThostFtdcQryTransferSerialField > pQryTransferSerial, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\u01e9\u053c\ufffd\ufffd\u03f5<br>
	 * Original signature : <code>int ReqQryAccountregister(CThostFtdcQryAccountregisterField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:615</i>
	 */
	@Virtual(68) 
	public native int ReqQryAccountregister(Pointer<CThostFtdcQryAccountregisterField > pQryAccountregister, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u01e9\u053c\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryContractBank(CThostFtdcQryContractBankField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:618</i>
	 */
	@Virtual(69) 
	public native int ReqQryContractBank(Pointer<CThostFtdcQryContractBankField > pQryContractBank, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0524\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryParkedOrder(CThostFtdcQryParkedOrderField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:621</i>
	 */
	@Virtual(70) 
	public native int ReqQryParkedOrder(Pointer<CThostFtdcQryParkedOrderField > pQryParkedOrder, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0524\ufffd\ud98f\uddf5\ufffd<br>
	 * Original signature : <code>int ReqQryParkedOrderAction(CThostFtdcQryParkedOrderActionField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:624</i>
	 */
	@Virtual(71) 
	public native int ReqQryParkedOrderAction(Pointer<CThostFtdcQryParkedOrderActionField > pQryParkedOrderAction, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>int ReqQryTradingNotice(CThostFtdcQryTradingNoticeField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:627</i>
	 */
	@Virtual(72) 
	public native int ReqQryTradingNotice(Pointer<CThostFtdcQryTradingNoticeField > pQryTradingNotice, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\u05f2\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryBrokerTradingParams(CThostFtdcQryBrokerTradingParamsField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:630</i>
	 */
	@Virtual(73) 
	public native int ReqQryBrokerTradingParams(Pointer<CThostFtdcQryBrokerTradingParamsField > pQryBrokerTradingParams, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd\ufffd\u3de8<br>
	 * Original signature : <code>int ReqQryBrokerTradingAlgos(CThostFtdcQryBrokerTradingAlgosField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:633</i>
	 */
	@Virtual(74) 
	public native int ReqQryBrokerTradingAlgos(Pointer<CThostFtdcQryBrokerTradingAlgosField > pQryBrokerTradingAlgos, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQueryCFMMCTradingAccountToken(CThostFtdcQueryCFMMCTradingAccountTokenField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:636</i>
	 */
	@Virtual(75) 
	public native int ReqQueryCFMMCTradingAccountToken(Pointer<CThostFtdcQueryCFMMCTradingAccountTokenField > pQueryCFMMCTradingAccountToken, int nRequestID);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\u05ea\ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqFromBankToFutureByFuture(CThostFtdcReqTransferField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:639</i>
	 */
	@Virtual(76) 
	public native int ReqFromBankToFutureByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, int nRequestID);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\ufffd\u02bd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqFromFutureToBankByFuture(CThostFtdcReqTransferField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:642</i>
	 */
	@Virtual(77) 
	public native int ReqFromFutureToBankByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, int nRequestID);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQueryBankAccountMoneyByFuture(CThostFtdcReqQueryAccountField*, int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:645</i>
	 */
	@Virtual(78) 
	public native int ReqQueryBankAccountMoneyByFuture(Pointer<CThostFtdcReqQueryAccountField > pReqQueryAccount, int nRequestID);
	/**
	 * Original signature : <code>void* LoadExtApi(void*, KS_EXTAPI_TYPE)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:655</i>
	 */
	@Virtual(79) 
	public native Pointer<? > LoadExtApi(Pointer<? > pSpi, IntValuedEnum<KS_EXTAPI_TYPE > nExtApiType);
	public CThostFtdcTraderApi(Pointer pointer) {
		super(pointer);
	}
}
