package kstraderapiex;
import ksuserapistructex.CThostFtdcAccountregisterField;
import ksuserapistructex.CThostFtdcBrokerTradingAlgosField;
import ksuserapistructex.CThostFtdcBrokerTradingParamsField;
import ksuserapistructex.CThostFtdcCFMMCTradingAccountKeyField;
import ksuserapistructex.CThostFtdcCFMMCTradingAccountTokenField;
import ksuserapistructex.CThostFtdcCancelAccountField;
import ksuserapistructex.CThostFtdcChangeAccountField;
import ksuserapistructex.CThostFtdcCombActionField;
import ksuserapistructex.CThostFtdcCombInstrumentGuardField;
import ksuserapistructex.CThostFtdcContractBankField;
import ksuserapistructex.CThostFtdcDepthMarketDataField;
import ksuserapistructex.CThostFtdcEWarrantOffsetField;
import ksuserapistructex.CThostFtdcErrorConditionalOrderField;
import ksuserapistructex.CThostFtdcExchangeField;
import ksuserapistructex.CThostFtdcExchangeMarginRateAdjustField;
import ksuserapistructex.CThostFtdcExchangeMarginRateField;
import ksuserapistructex.CThostFtdcExchangeRateField;
import ksuserapistructex.CThostFtdcExecOrderActionField;
import ksuserapistructex.CThostFtdcExecOrderField;
import ksuserapistructex.CThostFtdcForQuoteField;
import ksuserapistructex.CThostFtdcForQuoteRspField;
import ksuserapistructex.CThostFtdcInputCombActionField;
import ksuserapistructex.CThostFtdcInputExecOrderActionField;
import ksuserapistructex.CThostFtdcInputExecOrderField;
import ksuserapistructex.CThostFtdcInputForQuoteField;
import ksuserapistructex.CThostFtdcInputLockField;
import ksuserapistructex.CThostFtdcInputOrderActionField;
import ksuserapistructex.CThostFtdcInputOrderField;
import ksuserapistructex.CThostFtdcInputQuoteActionField;
import ksuserapistructex.CThostFtdcInputQuoteField;
import ksuserapistructex.CThostFtdcInstrumentCommissionRateField;
import ksuserapistructex.CThostFtdcInstrumentField;
import ksuserapistructex.CThostFtdcInstrumentMarginRateField;
import ksuserapistructex.CThostFtdcInstrumentOrderCommRateField;
import ksuserapistructex.CThostFtdcInstrumentStatusField;
import ksuserapistructex.CThostFtdcInvestorField;
import ksuserapistructex.CThostFtdcInvestorPositionCombineDetailField;
import ksuserapistructex.CThostFtdcInvestorPositionDetailField;
import ksuserapistructex.CThostFtdcInvestorPositionField;
import ksuserapistructex.CThostFtdcInvestorProductGroupMarginField;
import ksuserapistructex.CThostFtdcLockField;
import ksuserapistructex.CThostFtdcLockPositionField;
import ksuserapistructex.CThostFtdcNoticeField;
import ksuserapistructex.CThostFtdcNotifyQueryAccountField;
import ksuserapistructex.CThostFtdcOpenAccountField;
import ksuserapistructex.CThostFtdcOptionInstrCommRateField;
import ksuserapistructex.CThostFtdcOptionInstrTradeCostField;
import ksuserapistructex.CThostFtdcOrderActionField;
import ksuserapistructex.CThostFtdcOrderField;
import ksuserapistructex.CThostFtdcParkedOrderActionField;
import ksuserapistructex.CThostFtdcParkedOrderField;
import ksuserapistructex.CThostFtdcProductExchRateField;
import ksuserapistructex.CThostFtdcProductField;
import ksuserapistructex.CThostFtdcProductGroupField;
import ksuserapistructex.CThostFtdcQueryCFMMCTradingAccountTokenField;
import ksuserapistructex.CThostFtdcQueryMaxOrderVolumeField;
import ksuserapistructex.CThostFtdcQuoteActionField;
import ksuserapistructex.CThostFtdcQuoteField;
import ksuserapistructex.CThostFtdcRemoveParkedOrderActionField;
import ksuserapistructex.CThostFtdcRemoveParkedOrderField;
import ksuserapistructex.CThostFtdcReqQueryAccountField;
import ksuserapistructex.CThostFtdcReqRepealField;
import ksuserapistructex.CThostFtdcReqTransferField;
import ksuserapistructex.CThostFtdcRspAuthenticateField;
import ksuserapistructex.CThostFtdcRspInfoField;
import ksuserapistructex.CThostFtdcRspRepealField;
import ksuserapistructex.CThostFtdcRspTransferField;
import ksuserapistructex.CThostFtdcRspUserLoginField;
import ksuserapistructex.CThostFtdcSecAgentACIDMapField;
import ksuserapistructex.CThostFtdcSettlementInfoConfirmField;
import ksuserapistructex.CThostFtdcSettlementInfoField;
import ksuserapistructex.CThostFtdcTradeField;
import ksuserapistructex.CThostFtdcTradingAccountField;
import ksuserapistructex.CThostFtdcTradingAccountPasswordUpdateField;
import ksuserapistructex.CThostFtdcTradingCodeField;
import ksuserapistructex.CThostFtdcTradingNoticeField;
import ksuserapistructex.CThostFtdcTradingNoticeInfoField;
import ksuserapistructex.CThostFtdcTransferBankField;
import ksuserapistructex.CThostFtdcTransferSerialField;
import ksuserapistructex.CThostFtdcUserLogoutField;
import ksuserapistructex.CThostFtdcUserPasswordUpdateField;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Virtual;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : KSTraderApiEx.h:26</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSTraderApiEx") 
public class CThostFtdcTraderSpi extends CPPObject {
	public CThostFtdcTraderSpi() {
		super();
	}
	/**
	 * \ufffd\ufffd\ufffd\u037b\ufffd\ufffd\ufffd\ufffd\ubf7b\ufffd\u05fa\ufffd\u0328\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0368\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\ufffd\u03b4\ufffd\ufffd\u00bc\u01f0\ufffd\ufffd\ufffd\ufffd\ufffd\u00f7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00e1\ufffd<br>
	 * Original signature : <code>void OnFrontConnected()</code><br>
	 * <i>native declaration : KSTraderApiEx.h:30</i>
	 */
	@Virtual(0) 
	public native void OnFrontConnected();
	/**
	 * 0x2003 \ufffd\u0575\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>void OnFrontDisconnected(int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:39</i>
	 */
	@Virtual(1) 
	public native void OnFrontDisconnected(int nReason);
	/**
	 * @param nTimeLapse \ufffd\ufffd\ufffd\ufffd\ufffd\u03f4\u03bd\ufffd\ufffd\u0571\ufffd\ufffd\u0135\ufffd\u02b1\ufffd\ufffd<br>
	 * Original signature : <code>void OnHeartBeatWarning(int)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:43</i>
	 */
	@Virtual(2) 
	public native void OnHeartBeatWarning(int nTimeLapse);
	/**
	 * \ufffd\u037b\ufffd\ufffd\ufffd\ufffd\ufffd\u05a4\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspAuthenticate(CThostFtdcRspAuthenticateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:46</i>
	 */
	@Virtual(3) 
	public native void OnRspAuthenticate(Pointer<CThostFtdcRspAuthenticateField > pRspAuthenticateField, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspUserLogin(CThostFtdcRspUserLoginField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:50</i>
	 */
	@Virtual(4) 
	public native void OnRspUserLogin(Pointer<CThostFtdcRspUserLoginField > pRspUserLogin, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\u01f3\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspUserLogout(CThostFtdcUserLogoutField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:53</i>
	 */
	@Virtual(5) 
	public native void OnRspUserLogout(Pointer<CThostFtdcUserLogoutField > pUserLogout, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspUserPasswordUpdate(CThostFtdcUserPasswordUpdateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:56</i>
	 */
	@Virtual(6) 
	public native void OnRspUserPasswordUpdate(Pointer<CThostFtdcUserPasswordUpdateField > pUserPasswordUpdate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\u02bd\ufffd\ufffd\u02fb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspTradingAccountPasswordUpdate(CThostFtdcTradingAccountPasswordUpdateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:59</i>
	 */
	@Virtual(7) 
	public native void OnRspTradingAccountPasswordUpdate(Pointer<CThostFtdcTradingAccountPasswordUpdateField > pTradingAccountPasswordUpdate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspOrderInsert(CThostFtdcInputOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:62</i>
	 */
	@Virtual(8) 
	public native void OnRspOrderInsert(Pointer<CThostFtdcInputOrderField > pInputOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u0524\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspParkedOrderInsert(CThostFtdcParkedOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:65</i>
	 */
	@Virtual(9) 
	public native void OnRspParkedOrderInsert(Pointer<CThostFtdcParkedOrderField > pParkedOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u0524\ufffd\ud98f\uddf5\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspParkedOrderAction(CThostFtdcParkedOrderActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:68</i>
	 */
	@Virtual(10) 
	public native void OnRspParkedOrderAction(Pointer<CThostFtdcParkedOrderActionField > pParkedOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspOrderAction(CThostFtdcInputOrderActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:71</i>
	 */
	@Virtual(11) 
	public native void OnRspOrderAction(Pointer<CThostFtdcInputOrderActionField > pInputOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\udb86\ude35\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQueryMaxOrderVolume(CThostFtdcQueryMaxOrderVolumeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:74</i>
	 */
	@Virtual(12) 
	public native void OnRspQueryMaxOrderVolume(Pointer<CThostFtdcQueryMaxOrderVolumeField > pQueryMaxOrderVolume, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u0376\ufffd\ufffd\ufffd\u07fd\ufffd\ufffd\ufffd\ufffd\ufffd\u0237\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspSettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:77</i>
	 */
	@Virtual(13) 
	public native void OnRspSettlementInfoConfirm(Pointer<CThostFtdcSettlementInfoConfirmField > pSettlementInfoConfirm, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u027e\ufffd\ufffd\u0524\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspRemoveParkedOrder(CThostFtdcRemoveParkedOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:80</i>
	 */
	@Virtual(14) 
	public native void OnRspRemoveParkedOrder(Pointer<CThostFtdcRemoveParkedOrderField > pRemoveParkedOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u027e\ufffd\ufffd\u0524\ufffd\ud98f\uddf5\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspRemoveParkedOrderAction(CThostFtdcRemoveParkedOrderActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:83</i>
	 */
	@Virtual(15) 
	public native void OnRspRemoveParkedOrderAction(Pointer<CThostFtdcRemoveParkedOrderActionField > pRemoveParkedOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u05b4\ufffd\ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspExecOrderInsert(CThostFtdcInputExecOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:86</i>
	 */
	@Virtual(16) 
	public native void OnRspExecOrderInsert(Pointer<CThostFtdcInputExecOrderField > pInputExecOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u05b4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspExecOrderAction(CThostFtdcInputExecOrderActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:89</i>
	 */
	@Virtual(17) 
	public native void OnRspExecOrderAction(Pointer<CThostFtdcInputExecOrderActionField > pInputExecOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u046f\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspForQuoteInsert(CThostFtdcInputForQuoteField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:92</i>
	 */
	@Virtual(18) 
	public native void OnRspForQuoteInsert(Pointer<CThostFtdcInputForQuoteField > pInputForQuote, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQuoteInsert(CThostFtdcInputQuoteField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:95</i>
	 */
	@Virtual(19) 
	public native void OnRspQuoteInsert(Pointer<CThostFtdcInputQuoteField > pInputQuote, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\u06f2\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQuoteAction(CThostFtdcInputQuoteActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:98</i>
	 */
	@Virtual(20) 
	public native void OnRspQuoteAction(Pointer<CThostFtdcInputQuoteActionField > pInputQuoteAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\u04e6\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspLockInsert(CThostFtdcInputLockField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:101</i>
	 */
	@Virtual(21) 
	public native void OnRspLockInsert(Pointer<CThostFtdcInputLockField > pInputLock, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspCombActionInsert(CThostFtdcInputCombActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:104</i>
	 */
	@Virtual(22) 
	public native void OnRspCombActionInsert(Pointer<CThostFtdcInputCombActionField > pInputCombAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryOrder(CThostFtdcOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:107</i>
	 */
	@Virtual(23) 
	public native void OnRspQryOrder(Pointer<CThostFtdcOrderField > pOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\u027d\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryTrade(CThostFtdcTradeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:110</i>
	 */
	@Virtual(24) 
	public native void OnRspQryTrade(Pointer<CThostFtdcTradeField > pTrade, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\u07f3\u05b2\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryInvestorPosition(CThostFtdcInvestorPositionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:113</i>
	 */
	@Virtual(25) 
	public native void OnRspQryInvestorPosition(Pointer<CThostFtdcInvestorPositionField > pInvestorPosition, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\u02bd\ufffd\ufffd\u02fb\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryTradingAccount(CThostFtdcTradingAccountField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:116</i>
	 */
	@Virtual(26) 
	public native void OnRspQryTradingAccount(Pointer<CThostFtdcTradingAccountField > pTradingAccount, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryInvestor(CThostFtdcInvestorField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:119</i>
	 */
	@Virtual(27) 
	public native void OnRspQryInvestor(Pointer<CThostFtdcInvestorField > pInvestor, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\u05f1\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryTradingCode(CThostFtdcTradingCodeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:122</i>
	 */
	@Virtual(28) 
	public native void OnRspQryTradingCode(Pointer<CThostFtdcTradingCodeField > pTradingCode, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u053c\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryInstrumentMarginRate(CThostFtdcInstrumentMarginRateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:125</i>
	 */
	@Virtual(29) 
	public native void OnRspQryInstrumentMarginRate(Pointer<CThostFtdcInstrumentMarginRateField > pInstrumentMarginRate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryInstrumentCommissionRate(CThostFtdcInstrumentCommissionRateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:128</i>
	 */
	@Virtual(30) 
	public native void OnRspQryInstrumentCommissionRate(Pointer<CThostFtdcInstrumentCommissionRateField > pInstrumentCommissionRate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryExchange(CThostFtdcExchangeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:131</i>
	 */
	@Virtual(31) 
	public native void OnRspQryExchange(Pointer<CThostFtdcExchangeField > pExchange, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u01b7\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryProduct(CThostFtdcProductField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:134</i>
	 */
	@Virtual(32) 
	public native void OnRspQryProduct(Pointer<CThostFtdcProductField > pProduct, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u053c\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryInstrument(CThostFtdcInstrumentField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:137</i>
	 */
	@Virtual(33) 
	public native void OnRspQryInstrument(Pointer<CThostFtdcInstrumentField > pInstrument, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryDepthMarketData(CThostFtdcDepthMarketDataField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:140</i>
	 */
	@Virtual(34) 
	public native void OnRspQryDepthMarketData(Pointer<CThostFtdcDepthMarketDataField > pDepthMarketData, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\u07fd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQrySettlementInfo(CThostFtdcSettlementInfoField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:143</i>
	 */
	@Virtual(35) 
	public native void OnRspQrySettlementInfo(Pointer<CThostFtdcSettlementInfoField > pSettlementInfo, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryTransferBank(CThostFtdcTransferBankField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:146</i>
	 */
	@Virtual(36) 
	public native void OnRspQryTransferBank(Pointer<CThostFtdcTransferBankField > pTransferBank, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\u07f3\u05b2\ufffd\ufffd\ufffd\u03f8\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryInvestorPositionDetail(CThostFtdcInvestorPositionDetailField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:149</i>
	 */
	@Virtual(37) 
	public native void OnRspQryInvestorPositionDetail(Pointer<CThostFtdcInvestorPositionDetailField > pInvestorPositionDetail, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\u037b\ufffd\u0368\u05aa\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryNotice(CThostFtdcNoticeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:152</i>
	 */
	@Virtual(38) 
	public native void OnRspQryNotice(Pointer<CThostFtdcNoticeField > pNotice, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2\u0237\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQrySettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:155</i>
	 */
	@Virtual(39) 
	public native void OnRspQrySettlementInfoConfirm(Pointer<CThostFtdcSettlementInfoConfirmField > pSettlementInfoConfirm, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\u07f3\u05b2\ufffd\ufffd\ufffd\u03f8\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryInvestorPositionCombineDetail(CThostFtdcInvestorPositionCombineDetailField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:158</i>
	 */
	@Virtual(40) 
	public native void OnRspQryInvestorPositionCombineDetail(Pointer<CThostFtdcInvestorPositionCombineDetailField > pInvestorPositionCombineDetail, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\u03f5\u0373\ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\u02bd\ufffd\ufffd\u02fb\ufffd\ufffd\ufffd\u053f\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryCFMMCTradingAccountKey(CThostFtdcCFMMCTradingAccountKeyField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:161</i>
	 */
	@Virtual(41) 
	public native void OnRspQryCFMMCTradingAccountKey(Pointer<CThostFtdcCFMMCTradingAccountKeyField > pCFMMCTradingAccountKey, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\u05b5\ufffd\ufffd\u06f5\ufffd\ufffd\ufffd\u03e2\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryEWarrantOffset(CThostFtdcEWarrantOffsetField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:164</i>
	 */
	@Virtual(42) 
	public native void OnRspQryEWarrantOffset(Pointer<CThostFtdcEWarrantOffsetField > pEWarrantOffset, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0376\ufffd\ufffd\ufffd\ufffd\u01b7\ufffd\ufffd/\ufffd\ufffd\u01b7\ufffd\u05b1\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryInvestorProductGroupMargin(CThostFtdcInvestorProductGroupMarginField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:167</i>
	 */
	@Virtual(43) 
	public native void OnRspQryInvestorProductGroupMargin(Pointer<CThostFtdcInvestorProductGroupMarginField > pInvestorProductGroupMargin, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryExchangeMarginRate(CThostFtdcExchangeMarginRateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:170</i>
	 */
	@Virtual(44) 
	public native void OnRspQryExchangeMarginRate(Pointer<CThostFtdcExchangeMarginRateField > pExchangeMarginRate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryExchangeMarginRateAdjust(CThostFtdcExchangeMarginRateAdjustField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:173</i>
	 */
	@Virtual(45) 
	public native void OnRspQryExchangeMarginRateAdjust(Pointer<CThostFtdcExchangeMarginRateAdjustField > pExchangeMarginRateAdjust, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryExchangeRate(CThostFtdcExchangeRateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:176</i>
	 */
	@Virtual(46) 
	public native void OnRspQryExchangeRate(Pointer<CThostFtdcExchangeRateField > pExchangeRate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0531\ufffd\ufffd\ufffd\ufffd\u0228\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQrySecAgentACIDMap(CThostFtdcSecAgentACIDMapField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:179</i>
	 */
	@Virtual(47) 
	public native void OnRspQrySecAgentACIDMap(Pointer<CThostFtdcSecAgentACIDMapField > pSecAgentACIDMap, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u01b7\ufffd\ufffd\ufffd\u06fb\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspQryProductExchRate(CThostFtdcProductExchRateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:182</i>
	 */
	@Virtual(48) 
	public native void OnRspQryProductExchRate(Pointer<CThostFtdcProductExchRateField > pProductExchRate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u01b7\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspQryProductGroup(CThostFtdcProductGroupField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:185</i>
	 */
	@Virtual(49) 
	public native void OnRspQryProductGroup(Pointer<CThostFtdcProductGroupField > pProductGroup, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryInstrumentOrderCommRate(CThostFtdcInstrumentOrderCommRateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:188</i>
	 */
	@Virtual(50) 
	public native void OnRspQryInstrumentOrderCommRate(Pointer<CThostFtdcInstrumentOrderCommRateField > pInstrumentOrderCommRate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u0228\ufffd\ufffd\ufffd\u05f3\u0271\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryOptionInstrTradeCost(CThostFtdcOptionInstrTradeCostField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:191</i>
	 */
	@Virtual(51) 
	public native void OnRspQryOptionInstrTradeCost(Pointer<CThostFtdcOptionInstrTradeCostField > pOptionInstrTradeCost, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u0228\ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryOptionInstrCommRate(CThostFtdcOptionInstrCommRateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:194</i>
	 */
	@Virtual(52) 
	public native void OnRspQryOptionInstrCommRate(Pointer<CThostFtdcOptionInstrCommRateField > pOptionInstrCommRate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u05b4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryExecOrder(CThostFtdcExecOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:197</i>
	 */
	@Virtual(53) 
	public native void OnRspQryExecOrder(Pointer<CThostFtdcExecOrderField > pExecOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u046f\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryForQuote(CThostFtdcForQuoteField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:200</i>
	 */
	@Virtual(54) 
	public native void OnRspQryForQuote(Pointer<CThostFtdcForQuoteField > pForQuote, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryQuote(CThostFtdcQuoteField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:203</i>
	 */
	@Virtual(55) 
	public native void OnRspQryQuote(Pointer<CThostFtdcQuoteField > pQuote, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u04e6\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspQryLock(CThostFtdcLockField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:206</i>
	 */
	@Virtual(56) 
	public native void OnRspQryLock(Pointer<CThostFtdcLockField > pLock, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u05a4\u022f\ufffd\ufffd\u03bb\u04e6\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspQryLockPosition(CThostFtdcLockPositionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:209</i>
	 */
	@Virtual(57) 
	public native void OnRspQryLockPosition(Pointer<CThostFtdcLockPositionField > pLockPosition, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u03fa\ufffd\u053c\ufffd\ufffd\u022b\u03f5\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryCombInstrumentGuard(CThostFtdcCombInstrumentGuardField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:212</i>
	 */
	@Virtual(58) 
	public native void OnRspQryCombInstrumentGuard(Pointer<CThostFtdcCombInstrumentGuardField > pCombInstrumentGuard, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryCombAction(CThostFtdcCombActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:215</i>
	 */
	@Virtual(59) 
	public native void OnRspQryCombAction(Pointer<CThostFtdcCombActionField > pCombAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u05ea\ufffd\ufffd\ufffd\ufffd\u02ee\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryTransferSerial(CThostFtdcTransferSerialField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:218</i>
	 */
	@Virtual(60) 
	public native void OnRspQryTransferSerial(Pointer<CThostFtdcTransferSerialField > pTransferSerial, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\u01e9\u053c\ufffd\ufffd\u03f5\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryAccountregister(CThostFtdcAccountregisterField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:221</i>
	 */
	@Virtual(61) 
	public native void OnRspQryAccountregister(Pointer<CThostFtdcAccountregisterField > pAccountregister, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u04e6\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspError(CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:224</i>
	 */
	@Virtual(62) 
	public native void OnRspError(Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnOrder(CThostFtdcOrderField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:227</i>
	 */
	@Virtual(63) 
	public native void OnRtnOrder(Pointer<CThostFtdcOrderField > pOrder);
	/**
	 * \ufffd\u027d\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnTrade(CThostFtdcTradeField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:230</i>
	 */
	@Virtual(64) 
	public native void OnRtnTrade(Pointer<CThostFtdcTradeField > pTrade);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnOrderInsert(CThostFtdcInputOrderField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:233</i>
	 */
	@Virtual(65) 
	public native void OnErrRtnOrderInsert(Pointer<CThostFtdcInputOrderField > pInputOrder, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnOrderAction(CThostFtdcOrderActionField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:236</i>
	 */
	@Virtual(66) 
	public native void OnErrRtnOrderAction(Pointer<CThostFtdcOrderActionField > pOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd\u05f4\u032c\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnInstrumentStatus(CThostFtdcInstrumentStatusField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:239</i>
	 */
	@Virtual(67) 
	public native void OnRtnInstrumentStatus(Pointer<CThostFtdcInstrumentStatusField > pInstrumentStatus);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnTradingNotice(CThostFtdcTradingNoticeInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:242</i>
	 */
	@Virtual(68) 
	public native void OnRtnTradingNotice(Pointer<CThostFtdcTradingNoticeInfoField > pTradingNoticeInfo);
	/**
	 * \ufffd\ufffd\u02be\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0423\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>void OnRtnErrorConditionalOrder(CThostFtdcErrorConditionalOrderField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:245</i>
	 */
	@Virtual(69) 
	public native void OnRtnErrorConditionalOrder(Pointer<CThostFtdcErrorConditionalOrderField > pErrorConditionalOrder);
	/**
	 * \u05b4\ufffd\ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnExecOrder(CThostFtdcExecOrderField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:248</i>
	 */
	@Virtual(70) 
	public native void OnRtnExecOrder(Pointer<CThostFtdcExecOrderField > pExecOrder);
	/**
	 * \u05b4\ufffd\ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnExecOrderInsert(CThostFtdcInputExecOrderField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:251</i>
	 */
	@Virtual(71) 
	public native void OnErrRtnExecOrderInsert(Pointer<CThostFtdcInputExecOrderField > pInputExecOrder, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \u05b4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnExecOrderAction(CThostFtdcExecOrderActionField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:254</i>
	 */
	@Virtual(72) 
	public native void OnErrRtnExecOrderAction(Pointer<CThostFtdcExecOrderActionField > pExecOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \u046f\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnForQuoteInsert(CThostFtdcInputForQuoteField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:257</i>
	 */
	@Virtual(73) 
	public native void OnErrRtnForQuoteInsert(Pointer<CThostFtdcInputForQuoteField > pInputForQuote, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnQuote(CThostFtdcQuoteField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:260</i>
	 */
	@Virtual(74) 
	public native void OnRtnQuote(Pointer<CThostFtdcQuoteField > pQuote);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnQuoteInsert(CThostFtdcInputQuoteField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:263</i>
	 */
	@Virtual(75) 
	public native void OnErrRtnQuoteInsert(Pointer<CThostFtdcInputQuoteField > pInputQuote, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \ufffd\ufffd\ufffd\u06f2\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnQuoteAction(CThostFtdcQuoteActionField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:266</i>
	 */
	@Virtual(76) 
	public native void OnErrRtnQuoteAction(Pointer<CThostFtdcQuoteActionField > pQuoteAction, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \u046f\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnForQuoteRsp(CThostFtdcForQuoteRspField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:269</i>
	 */
	@Virtual(77) 
	public native void OnRtnForQuoteRsp(Pointer<CThostFtdcForQuoteRspField > pForQuoteRsp);
	/**
	 * \ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>void OnRtnCFMMCTradingAccountToken(CThostFtdcCFMMCTradingAccountTokenField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:272</i>
	 */
	@Virtual(78) 
	public native void OnRtnCFMMCTradingAccountToken(Pointer<CThostFtdcCFMMCTradingAccountTokenField > pCFMMCTradingAccountToken);
	/**
	 * \ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnLock(CThostFtdcLockField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:275</i>
	 */
	@Virtual(79) 
	public native void OnRtnLock(Pointer<CThostFtdcLockField > pLock);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnErrRtnLockInsert(CThostFtdcInputLockField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:278</i>
	 */
	@Virtual(80) 
	public native void OnErrRtnLockInsert(Pointer<CThostFtdcInputLockField > pInputLock, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnCombAction(CThostFtdcCombActionField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:281</i>
	 */
	@Virtual(81) 
	public native void OnRtnCombAction(Pointer<CThostFtdcCombActionField > pCombAction);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnCombActionInsert(CThostFtdcInputCombActionField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:284</i>
	 */
	@Virtual(82) 
	public native void OnErrRtnCombActionInsert(Pointer<CThostFtdcInputCombActionField > pInputCombAction, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u01e9\u053c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryContractBank(CThostFtdcContractBankField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:287</i>
	 */
	@Virtual(83) 
	public native void OnRspQryContractBank(Pointer<CThostFtdcContractBankField > pContractBank, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0524\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryParkedOrder(CThostFtdcParkedOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:290</i>
	 */
	@Virtual(84) 
	public native void OnRspQryParkedOrder(Pointer<CThostFtdcParkedOrderField > pParkedOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\u0524\ufffd\ud98f\uddf5\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryParkedOrderAction(CThostFtdcParkedOrderActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:293</i>
	 */
	@Virtual(85) 
	public native void OnRspQryParkedOrderAction(Pointer<CThostFtdcParkedOrderActionField > pParkedOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\u0368\u05aa\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryTradingNotice(CThostFtdcTradingNoticeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:296</i>
	 */
	@Virtual(86) 
	public native void OnRspQryTradingNotice(Pointer<CThostFtdcTradingNoticeField > pTradingNotice, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\u05f2\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryBrokerTradingParams(CThostFtdcBrokerTradingParamsField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:299</i>
	 */
	@Virtual(87) 
	public native void OnRspQryBrokerTradingParams(Pointer<CThostFtdcBrokerTradingParamsField > pBrokerTradingParams, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\ufffd\ufffd\u3de8\ufffd\ufffd\u04e6<br>
	 * Original signature : <code>void OnRspQryBrokerTradingAlgos(CThostFtdcBrokerTradingAlgosField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:302</i>
	 */
	@Virtual(88) 
	public native void OnRspQryBrokerTradingAlgos(Pointer<CThostFtdcBrokerTradingAlgosField > pBrokerTradingAlgos, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspQueryCFMMCTradingAccountToken(CThostFtdcQueryCFMMCTradingAccountTokenField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:305</i>
	 */
	@Virtual(89) 
	public native void OnRspQueryCFMMCTradingAccountToken(Pointer<CThostFtdcQueryCFMMCTradingAccountTokenField > pQueryCFMMCTradingAccountToken, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\u0437\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\u05ea\ufffd\u06bb\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnFromBankToFutureByBank(CThostFtdcRspTransferField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:308</i>
	 */
	@Virtual(90) 
	public native void OnRtnFromBankToFutureByBank(Pointer<CThostFtdcRspTransferField > pRspTransfer);
	/**
	 * \ufffd\ufffd\ufffd\u0437\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\ufffd\u02bd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnFromFutureToBankByBank(CThostFtdcRspTransferField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:311</i>
	 */
	@Virtual(91) 
	public native void OnRtnFromFutureToBankByBank(Pointer<CThostFtdcRspTransferField > pRspTransfer);
	/**
	 * \ufffd\ufffd\ufffd\u0437\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05ea\ufffd\u06bb\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnRepealFromBankToFutureByBank(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:314</i>
	 */
	@Virtual(92) 
	public native void OnRtnRepealFromBankToFutureByBank(Pointer<CThostFtdcRspRepealField > pRspRepeal);
	/**
	 * \ufffd\ufffd\ufffd\u0437\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnRepealFromFutureToBankByBank(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:317</i>
	 */
	@Virtual(93) 
	public native void OnRtnRepealFromFutureToBankByBank(Pointer<CThostFtdcRspRepealField > pRspRepeal);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\u05ea\ufffd\u06bb\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnFromBankToFutureByFuture(CThostFtdcRspTransferField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:320</i>
	 */
	@Virtual(94) 
	public native void OnRtnFromBankToFutureByFuture(Pointer<CThostFtdcRspTransferField > pRspTransfer);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\ufffd\u02bd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnFromFutureToBankByFuture(CThostFtdcRspTransferField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:323</i>
	 */
	@Virtual(95) 
	public native void OnRtnFromFutureToBankByFuture(Pointer<CThostFtdcRspTransferField > pRspTransfer);
	/**
	 * \u03f5\u0373\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\u05b9\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05ea\ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0434\ufffd\ufffd\ufffd\ufffd\ufffd\u03fa\ufffd\ufffd\u0337\ufffd\ufffd\u0635\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnRepealFromBankToFutureByFutureManual(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:326</i>
	 */
	@Virtual(96) 
	public native void OnRtnRepealFromBankToFutureByFutureManual(Pointer<CThostFtdcRspRepealField > pRspRepeal);
	/**
	 * \u03f5\u0373\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\u05b9\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0434\ufffd\ufffd\ufffd\ufffd\ufffd\u03fa\ufffd\ufffd\u0337\ufffd\ufffd\u0635\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnRepealFromFutureToBankByFutureManual(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:329</i>
	 */
	@Virtual(97) 
	public native void OnRtnRepealFromFutureToBankByFutureManual(Pointer<CThostFtdcRspRepealField > pRspRepeal);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnQueryBankBalanceByFuture(CThostFtdcNotifyQueryAccountField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:332</i>
	 */
	@Virtual(98) 
	public native void OnRtnQueryBankBalanceByFuture(Pointer<CThostFtdcNotifyQueryAccountField > pNotifyQueryAccount);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\u05ea\ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnBankToFutureByFuture(CThostFtdcReqTransferField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:335</i>
	 */
	@Virtual(99) 
	public native void OnErrRtnBankToFutureByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\ufffd\u02bd\ufffd\u05ea\ufffd\ufffd\ufffd\u0434\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnFutureToBankByFuture(CThostFtdcReqTransferField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:338</i>
	 */
	@Virtual(100) 
	public native void OnErrRtnFutureToBankByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \u03f5\u0373\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\u05b9\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05ea\ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnRepealBankToFutureByFutureManual(CThostFtdcReqRepealField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:341</i>
	 */
	@Virtual(101) 
	public native void OnErrRtnRepealBankToFutureByFutureManual(Pointer<CThostFtdcReqRepealField > pReqRepeal, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \u03f5\u0373\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\u05b9\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\u05ea\ufffd\ufffd\ufffd\u0434\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnRepealFutureToBankByFutureManual(CThostFtdcReqRepealField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:344</i>
	 */
	@Virtual(102) 
	public native void OnErrRtnRepealFutureToBankByFutureManual(Pointer<CThostFtdcReqRepealField > pReqRepeal, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0631\ufffd<br>
	 * Original signature : <code>void OnErrRtnQueryBankBalanceByFuture(CThostFtdcReqQueryAccountField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:347</i>
	 */
	@Virtual(103) 
	public native void OnErrRtnQueryBankBalanceByFuture(Pointer<CThostFtdcReqQueryAccountField > pReqQueryAccount, Pointer<CThostFtdcRspInfoField > pRspInfo);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05ea\ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0434\ufffd\ufffd\ufffd\ufffd\ufffd\u03fa\ufffd\ufffd\u0337\ufffd\ufffd\u0635\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnRepealFromBankToFutureByFuture(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:350</i>
	 */
	@Virtual(104) 
	public native void OnRtnRepealFromBankToFutureByFuture(Pointer<CThostFtdcRspRepealField > pRspRepeal);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0434\ufffd\ufffd\ufffd\ufffd\ufffd\u03fa\ufffd\ufffd\u0337\ufffd\ufffd\u0635\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnRepealFromFutureToBankByFuture(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:353</i>
	 */
	@Virtual(105) 
	public native void OnRtnRepealFromFutureToBankByFuture(Pointer<CThostFtdcRspRepealField > pRspRepeal);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\u05ea\ufffd\u06bb\ufffd\u04e6\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspFromBankToFutureByFuture(CThostFtdcReqTransferField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:356</i>
	 */
	@Virtual(106) 
	public native void OnRspFromBankToFutureByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\ufffd\u02bd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\u04e6\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspFromFutureToBankByFuture(CThostFtdcReqTransferField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:359</i>
	 */
	@Virtual(107) 
	public native void OnRspFromFutureToBankByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6\ufffd\ufffd<br>
	 * Original signature : <code>void OnRspQueryBankAccountMoneyByFuture(CThostFtdcReqQueryAccountField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:362</i>
	 */
	@Virtual(108) 
	public native void OnRspQueryBankAccountMoneyByFuture(Pointer<CThostFtdcReqQueryAccountField > pReqQueryAccount, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \ufffd\ufffd\ufffd\u0437\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06bf\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnOpenAccountByBank(CThostFtdcOpenAccountField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:365</i>
	 */
	@Virtual(109) 
	public native void OnRtnOpenAccountByBank(Pointer<CThostFtdcOpenAccountField > pOpenAccount);
	/**
	 * \ufffd\ufffd\ufffd\u0437\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnCancelAccountByBank(CThostFtdcCancelAccountField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:368</i>
	 */
	@Virtual(110) 
	public native void OnRtnCancelAccountByBank(Pointer<CThostFtdcCancelAccountField > pCancelAccount);
	/**
	 * \ufffd\ufffd\ufffd\u0437\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02fa\ufffd\u0368\u05aa<br>
	 * Original signature : <code>void OnRtnChangeAccountByBank(CThostFtdcChangeAccountField*)</code><br>
	 * <i>native declaration : KSTraderApiEx.h:371</i>
	 */
	@Virtual(111) 
	public native void OnRtnChangeAccountByBank(Pointer<CThostFtdcChangeAccountField > pChangeAccount);
	public CThostFtdcTraderSpi(Pointer pointer) {
		super(pointer);
	}
}
