package ksvocapi;
import ksuserapistructex.CThostFtdcQryInvestorPositionCombineDetailField;
import ksuserapistructex.CThostFtdcQryInvestorPositionDetailField;
import ksvocapistruct.CKSCloseStrategy;
import ksvocapistruct.CKSCombStrategy;
import ksvocapistruct.CKSInputFundOutCreditApplyField;
import ksvocapistruct.CKSLargeFundOutApplyField;
import ksvocapistruct.CKSOptionCombStrategy;
import ksvocapistruct.CKSQryFundOutCreditApplyField;
import ksvocapistruct.CKSQryFundOutCreditField;
import ksvocapistruct.CKSQryInstrumentMarginRateField;
import ksvocapistruct.CKSQryLargeFundOutApplyField;
import ksvocapistruct.CKSQryMaxCombActionVolumeField;
import ksvocapistruct.CKSQryOptionInstrCommRateField;
import ksvocapistruct.CKSQryOptionMarginField;
import ksvocapistruct.CKSQryTradingNoticeField;
import ksvocapistruct.CKSQryTradingParamsField;
import ksvocapistruct.CKSQryUserProductUrlField;
import ksvocapistruct.CKSReqEMailLoginField;
import ksvocapistruct.CKSTransferInfo;
import ksvocapistruct.CThostFtdcBulkCancelOrderField;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Virtual;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : KSVocApi.h:84</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSVocApi") 
public class CKSVocApi extends CPPObject {
	public CKSVocApi() {
		super();
	}
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\u0133\u05b2\ufffd\ufffd\ufffd\u03f8<br>
	 * Original signature : <code>int ReqQueryInvestorOpenPosition(CThostFtdcQryInvestorPositionDetailField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:88</i>
	 */
	@Virtual(0) 
	public native int ReqQueryInvestorOpenPosition(Pointer<CThostFtdcQryInvestorPositionDetailField > pQryInvestorOpenPosition, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\ufffd\ufffd\ufffd\u03f3\u05b2\ufffd\ufffd\ufffd\u03f8<br>
	 * Original signature : <code>int ReqQueryInvestorOpenCombinePosition(CThostFtdcQryInvestorPositionCombineDetailField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:91</i>
	 */
	@Virtual(1) 
	public native int ReqQueryInvestorOpenCombinePosition(Pointer<CThostFtdcQryInvestorPositionCombineDetailField > pQryInvestorOpenCombinePosition, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqBulkCancelOrder(CThostFtdcBulkCancelOrderField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:94</i>
	 */
	@Virtual(2) 
	public native int ReqBulkCancelOrder(Pointer<CThostFtdcBulkCancelOrderField > pBulkCancelOrder, int nRequestID);
	/**
	 * \u01bd\ufffd\u05b2\ufffd\ufffd\u0532\ufffd\u046f\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryCloseStrategy(CKSCloseStrategy*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:97</i>
	 */
	@Virtual(3) 
	public native int ReqQryCloseStrategy(Pointer<CKSCloseStrategy > pCloseStrategy, int nRequestID);
	/**
	 * \ufffd\ufffd\u03f2\ufffd\ufffd\u0532\ufffd\u046f\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryCombStrategy(CKSCombStrategy*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:100</i>
	 */
	@Virtual(4) 
	public native int ReqQryCombStrategy(Pointer<CKSCombStrategy > pCombStrategy, int nRequestID);
	/**
	 * \ufffd\ufffd\u0228\ufffd\ufffd\u03f2\ufffd\ufffd\u0532\ufffd\u046f\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryOptionCombStrategy(CKSOptionCombStrategy*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:103</i>
	 */
	@Virtual(5) 
	public native int ReqQryOptionCombStrategy(Pointer<CKSOptionCombStrategy > pOptionCombStrategy, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\u037b\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * Original signature : <code>int ReqQryTransferInfo(CKSTransferInfo*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:106</i>
	 */
	@Virtual(6) 
	public native int ReqQryTransferInfo(Pointer<CKSTransferInfo > pTransferInfo, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\u0368\u05aa<br>
	 * Original signature : <code>int ReqQryKSTradingNotice(CKSQryTradingNoticeField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:109</i>
	 */
	@Virtual(7) 
	public native int ReqQryKSTradingNotice(Pointer<CKSQryTradingNoticeField > pQryTradingNotice, int nRequestID);
	/**
	 * \ufffd\u00fb\ufffd\ufffd\u02f2\ufffd\u01b7\ufffd\ufffd\u0534\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryUserProductUrl(CKSQryUserProductUrlField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:112</i>
	 */
	@Virtual(8) 
	public native int ReqQryUserProductUrl(Pointer<CKSQryUserProductUrlField > pQryUserProductUrl, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u03f2\ufffd\u05b5\ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryMaxCombActionVolume(CKSQryMaxCombActionVolumeField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:115</i>
	 */
	@Virtual(9) 
	public native int ReqQryMaxCombActionVolume(Pointer<CKSQryMaxCombActionVolumeField > pQryMaxCombActionVolume, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u0228\ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryKSOptionInstrCommRate(CKSQryOptionInstrCommRateField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:118</i>
	 */
	@Virtual(10) 
	public native int ReqQryKSOptionInstrCommRate(Pointer<CKSQryOptionInstrCommRateField > pQryOptionInstrCommRate, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\u053c\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryKSInstrumentMarginRate(CKSQryInstrumentMarginRateField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:121</i>
	 */
	@Virtual(11) 
	public native int ReqQryKSInstrumentMarginRate(Pointer<CKSQryInstrumentMarginRateField > pQryInstrumentMarginRate, int nRequestID);
	/**
	 * \ufffd\u037b\ufffd\u00ff\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqFundOutCreditApply(CKSInputFundOutCreditApplyField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:124</i>
	 */
	@Virtual(12) 
	public native int ReqFundOutCreditApply(Pointer<CKSInputFundOutCreditApplyField > pFundOutCreditApply, int nRequestID);
	/**
	 * \ufffd\u037b\ufffd\u00ff\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\u0232\ufffd\u046f<br>
	 * Original signature : <code>int ReqQryFundOutCredit(CKSQryFundOutCreditField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:127</i>
	 */
	@Virtual(13) 
	public native int ReqQryFundOutCredit(Pointer<CKSQryFundOutCreditField > pQryFundOutCredit, int nRequestID);
	/**
	 * \ufffd\u037b\ufffd\u00ff\ufffd\u0573\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u046f<br>
	 * Original signature : <code>int ReqQryFundOutCreditApply(CKSQryFundOutCreditApplyField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:130</i>
	 */
	@Virtual(14) 
	public native int ReqQryFundOutCreditApply(Pointer<CKSQryFundOutCreditApplyField > pQryFundOutCreditApply, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0524\u053c\ufffd\ufffd\u0221\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqLargeFundOutApply(CKSLargeFundOutApplyField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:133</i>
	 */
	@Virtual(15) 
	public native int ReqLargeFundOutApply(Pointer<CKSLargeFundOutApplyField > pLargeFundOutApply, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0524\u053c\ufffd\ufffd\u046f<br>
	 * Original signature : <code>int ReqQryLargeFundOutApply(CKSQryLargeFundOutApplyField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:136</i>
	 */
	@Virtual(16) 
	public native int ReqQryLargeFundOutApply(Pointer<CKSQryLargeFundOutApplyField > pQryLargeFundOutApply, int nRequestID);
	/**
	 * \ufffd\u07fb\ufffd\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqKSEMailLogin(CKSReqEMailLoginField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:139</i>
	 */
	@Virtual(17) 
	public native int ReqKSEMailLogin(Pointer<CKSReqEMailLoginField > pReqEMailLoginField, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\u0275\ufffd\ufffd\u0171\ufffd\u05a4\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryKSOptionMargin(CKSQryOptionMarginField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:142</i>
	 */
	@Virtual(18) 
	public native int ReqQryKSOptionMargin(Pointer<CKSQryOptionMarginField > pQryOptionMargin, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046fKS\ufffd\ufffd\ufffd\u05f2\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryKSTradingParams(CKSQryTradingParamsField*, int)</code><br>
	 * <i>native declaration : KSVocApi.h:145</i>
	 */
	@Virtual(19) 
	public native int ReqQryKSTradingParams(Pointer<CKSQryTradingParamsField > pQryTradingParams, int nRequestID);
	public CKSVocApi(Pointer pointer) {
		super(pointer);
	}
}
