package ksoptionapi;
import ksvocapistruct.CKSAutoExecOrderActionField;
import ksvocapistruct.CKSInputCombActionField;
import ksvocapistruct.CKSInputQuoteUpdateField;
import ksvocapistruct.CKSPositionLimitVolField;
import ksvocapistruct.CKSPurchaseLimitAmtField;
import ksvocapistruct.CKSQryCombActionVolumeField;
import ksvocapistruct.CKSQryExecOrderVolumeField;
import ksvocapistruct.CKSQryHistoryAssignmentField;
import ksvocapistruct.CKSQryHistoryOrderField;
import ksvocapistruct.CKSQryHistoryTradeField;
import ksvocapistruct.CKSQryIndexPriceField;
import ksvocapistruct.CKSQryInvestorPositionCombineDetailField;
import ksvocapistruct.CKSQryInvestorTradeLevelField;
import ksvocapistruct.CKSQryOptLimitField;
import ksvocapistruct.CKSQryOptionInstrGuardField;
import ksvocapistruct.CKSQrySODelivDetailField;
import ksvocapistruct.CKSQryStockOptionAssignmentField;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Virtual;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : KSOptionApi.h:87</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("KSOptionApi") 
public class CKSOptionApi extends CPPObject {
	public CKSOptionApi() {
		super();
	}
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\u05b8\ufffd\u05bb\ufffd\u05b8\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryIndexPrice(CKSQryIndexPriceField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:91</i>
	 */
	@Virtual(0) 
	public native int ReqQryIndexPrice(Pointer<CKSQryIndexPriceField > pIndexPrice, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\u0228\ufffd\ufffd\u053c\ufffd\ufffd\ufffd\ufffd\u03f5\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryOptionInstrGuard(CKSQryOptionInstrGuardField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:94</i>
	 */
	@Virtual(1) 
	public native int ReqQryOptionInstrGuard(Pointer<CKSQryOptionInstrGuardField > pQryOptionInstrGuard, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryExecOrderVolume(CKSQryExecOrderVolumeField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:97</i>
	 */
	@Virtual(2) 
	public native int ReqQryExecOrderVolume(Pointer<CKSQryExecOrderVolumeField > pQryExecOrderVolume, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0228\u05b8\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * Original signature : <code>int ReqQryStockOptionAssignment(CKSQryStockOptionAssignmentField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:100</i>
	 */
	@Virtual(3) 
	public native int ReqQryStockOptionAssignment(Pointer<CKSQryStockOptionAssignmentField > pQryStockOptionAssignment, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\u037b\ufffd\ufffd\ufffd\ufffd\u05fc\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryInvestorTradeLevel(CKSQryInvestorTradeLevelField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:103</i>
	 */
	@Virtual(4) 
	public native int ReqQryInvestorTradeLevel(Pointer<CKSQryInvestorTradeLevelField > pQryInvestorTradeLevel, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\u03f5\u0373\ufffd\ufffd\ufffd\ufffd\ufffd\u07b9\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryPurchaseLimitAmtT(CKSQryOptLimitField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:106</i>
	 */
	@Virtual(5) 
	public native int ReqQryPurchaseLimitAmtT(Pointer<CKSQryOptLimitField > pQryPurchaseLimitAmt, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\u03f5\u0373\ufffd\ufffd\ufffd\ufffd\ufffd\u07b2\u05b6\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryPositionLimitVolT(CKSQryOptLimitField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:109</i>
	 */
	@Virtual(6) 
	public native int ReqQryPositionLimitVolT(Pointer<CKSQryOptLimitField > pQryPositionLimitVol, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\u03f5\u0373\ufffd\ufffd\ufffd\ufffd\ufffd\u07b9\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryPurchaseLimitAmtS(CKSQryOptLimitField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:112</i>
	 */
	@Virtual(7) 
	public native int ReqQryPurchaseLimitAmtS(Pointer<CKSQryOptLimitField > pQryPurchaseLimitAmt, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\u03f5\u0373\ufffd\ufffd\ufffd\ufffd\ufffd\u07b2\u05b6\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryPositionLimitVolS(CKSQryOptLimitField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:115</i>
	 */
	@Virtual(8) 
	public native int ReqQryPositionLimitVolS(Pointer<CKSQryOptLimitField > pQryPositionLimitVol, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u07b9\ufffd\ufffd\ufffd\u0231\ufffd\ufffd<br>
	 * Original signature : <code>int ReqPurchaseLimitAmtUpdate(CKSPurchaseLimitAmtField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:118</i>
	 */
	@Virtual(9) 
	public native int ReqPurchaseLimitAmtUpdate(Pointer<CKSPurchaseLimitAmtField > pPurchaseLimitAmt, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u07b2\u05b6\ufffd\u0231\ufffd\ufffd<br>
	 * Original signature : <code>int ReqPositionLimitVolUpdate(CKSPositionLimitVolField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:121</i>
	 */
	@Virtual(10) 
	public native int ReqPositionLimitVolUpdate(Pointer<CKSPositionLimitVolField > pPositionLimitVol, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02b7\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryHistoryOrder(CKSQryHistoryOrderField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:124</i>
	 */
	@Virtual(11) 
	public native int ReqQryHistoryOrder(Pointer<CKSQryHistoryOrderField > pQryHistoryOrder, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02b7\ufffd\u027d\ufffd<br>
	 * Original signature : <code>int ReqQryHistoryTrade(CKSQryHistoryTradeField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:127</i>
	 */
	@Virtual(12) 
	public native int ReqQryHistoryTrade(Pointer<CKSQryHistoryTradeField > pQryHistoryTrade, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02b7\ufffd\ufffd\u0228\u05b8\ufffd\ufffd\ufffd\ufffd\u03f8<br>
	 * Original signature : <code>int ReqQryStockOptionHistoryAssignment(CKSQryHistoryAssignmentField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:130</i>
	 */
	@Virtual(13) 
	public native int ReqQryStockOptionHistoryAssignment(Pointer<CKSQryHistoryAssignmentField > pQryHistoryAssignment, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0228\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03f8<br>
	 * Original signature : <code>int ReqQryStockOptionDelivDetail(CKSQrySODelivDetailField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:133</i>
	 */
	@Virtual(14) 
	public native int ReqQryStockOptionDelivDetail(Pointer<CKSQrySODelivDetailField > pQrySODelivDetail, int nRequestID);
	/**
	 * \ufffd\u0536\ufffd\ufffd\ufffd\u0228\u05b4\ufffd\u0432\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqAutoExecOrderAction(CKSAutoExecOrderActionField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:136</i>
	 */
	@Virtual(15) 
	public native int ReqAutoExecOrderAction(Pointer<CKSAutoExecOrderActionField > pAutoExecOrderAction, int nRequestID);
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03f2\ufffd\ufffd\u03af\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqCombActionInsert(CKSInputCombActionField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:139</i>
	 */
	@Virtual(16) 
	public native int ReqCombActionInsert(Pointer<CKSInputCombActionField > pInputCombAction, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03f3\u05b2\ufffd\ufffd\ufffd\u03f8<br>
	 * Original signature : <code>int ReqQryInvestorCombinePosition(CKSQryInvestorPositionCombineDetailField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:142</i>
	 */
	@Virtual(17) 
	public native int ReqQryInvestorCombinePosition(Pointer<CKSQryInvestorPositionCombineDetailField > pQryInvestorCombinePosition, int nRequestID);
	/**
	 * \ufffd\ufffd\u046f\ufffd\ufffd\ufffd\u027f\ufffd\ufffd\ufffd\u03ff\u0272\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQryCombActionVolume(CKSQryCombActionVolumeField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:145</i>
	 */
	@Virtual(18) 
	public native int ReqQryCombActionVolume(Pointer<CKSQryCombActionVolumeField > pQryCombActionVolume, int nRequestID);
	/**
	 * \ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\u0331\ufffd\ufffd\u06f5\ufffd\ufffd\u07b8\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * Original signature : <code>int ReqQuoteUpdate(CKSInputQuoteUpdateField*, int)</code><br>
	 * <i>native declaration : KSOptionApi.h:148</i>
	 */
	@Virtual(19) 
	public native int ReqQuoteUpdate(Pointer<CKSInputQuoteUpdateField > pInputQuoteUpdate, int nRequestID);
	public CKSOptionApi(Pointer pointer) {
		super(pointer);
	}
}
